/**
 * @file   ProbeCommVariant.cpp
 * @brief  Implementation of ProbeCommVariant component.
 * @details Portable C++ implementation generated by
 *          the Code Generation Pipeline.
 *          Uses runtime::IRuntime for all platform-dependent behavior.
 * @author  Engineering Team
 * @version 1.0.0
 * @copyright Copyright (c) 2024 Company. All rights reserved.
 */

#include "ProbeCommVariant.hpp"
#include <array>
#include <cerrno>
#include <cstdint>
#include <cstring>
#include <fstream>
#include <iostream>
#include <optional>
#include <sstream>
#include <string>
#include <vector>

// ---------------------------------------------------------------------------
// Forward declaration of the concrete shared-memory abstraction used by
// ReadVariantCode().  Icmem_ReadVariantCode is the low-level C function
// exposed by the ExternalSharedMemory component (SharedMemory_Variant_Service).
// Its signature is:  int8_t Icmem_ReadVariantCode(uint8_t* out_bytes, uint8_t len)
// Return value: 0 on success, negative EN_RET_CODE on failure.
// ---------------------------------------------------------------------------
extern "C" int8_t Icmem_ReadVariantCode(uint8_t* out_bytes, uint8_t len);

// ---------------------------------------------------------------------------
// Internal file-scope helpers — not part of the class interface.
// ---------------------------------------------------------------------------

namespace
{

/**
 * @brief   Result type returned by the shared-memory variant read abstraction.
 * @details Aggregates the success flag and the resolved variant code value so
 *          that ReadVariantCode() can follow the pseudocode pattern exactly.
 */
struct SharedMemReadResult
{
    bool        success{false};  ///< @brief True when Icmem_ReadVariantCode returned 0.
    std::string value{};         ///< @brief 5-character ASCII variant code on success.
};

/**
 * @brief   Concrete abstraction over Icmem_ReadVariantCode.
 * @details Calls the low-level C interface, converts the raw uint8_t byte array
 *          into a std::string, and returns a SharedMemReadResult.  This function
 *          implements the SharedMemory_VariantCode.Read() call mandated by the
 *          pseudocode.
 * @return  SharedMemReadResult with success == true and a 5-char value on success;
 *          success == false otherwise.
 */
SharedMemReadResult SharedMemory_VariantCode_Read() noexcept
{
    SharedMemReadResult result{};

    static constexpr uint8_t kRawLen{5U};
    std::array<uint8_t, kRawLen> rawBytes{};
    rawBytes.fill(0U);

    const int8_t retCode{Icmem_ReadVariantCode(rawBytes.data(), kRawLen)};

    if (retCode == static_cast<int8_t>(0))
    {
        std::string decoded{};
        decoded.reserve(kRawLen);
        for (uint8_t idx{0U}; idx < kRawLen; ++idx)
        {
            decoded += static_cast<char>(rawBytes[idx]);
        }
        result.success = true;
        result.value   = decoded;
    }
    else
    {
        result.success = false;
    }

    return result;
}

// ---------------------------------------------------------------------------
// Minimal JSON dictionary abstractions used by SetVariant().
// The variant_table.json is expected to have the following structure:
//
//  {
//    "variants": [
//      {
//        "code"                        : "AB123",
//        "regularProbeValue"           : "A",
//        "eventProbeValue"             : "A",
//        "eventProbeWithoutPictureValue": "-",
//        "gedrValue"                   : "A",
//        "gedrWithoutPictureValue"     : "-"
//      },
//      ...
//    ]
//  }
//
// The parser below is a hand-written, allocation-minimal JSON reader that
// satisfies the no-dynamic-memory and no-external-library constraints.
// ---------------------------------------------------------------------------

/**
 * @brief   Represents a single resolved variant dictionary entry.
 * @details Populated by FindEntry() when a matching variant code is located
 *          inside the loaded dictionary.
 */
struct DictionaryEntry
{
    bool        found{false};                        ///< @brief True when the code was matched.
    std::string regularProbeValue{};                 ///< @brief Activation value for Regular Probe.
    std::string eventProbeValue{};                   ///< @brief Activation value for Event Probe.
    std::string eventProbeWithoutPictureValue{};     ///< @brief Activation value for Event Probe w/o picture.
    std::string gedrValue{};                         ///< @brief Activation value for GEDR.
    std::string gedrWithoutPictureValue{};           ///< @brief Activation value for GEDR w/o picture.
};

/**
 * @brief   Represents the result of loading the variant dictionary file.
 * @details Holds the raw JSON content and a success flag.  FindEntry() operates
 *          on this object to locate a specific variant code entry.
 */
struct DictionaryLoadResult
{
    bool        success{false};  ///< @brief True when the file was opened and read without error.
    std::string jsonContent{};   ///< @brief Raw JSON text of the dictionary file.

    /**
     * @brief   Searches the loaded JSON content for a variant entry matching @p code.
     * @details Performs a simple string-based search through the JSON content.
     *          Extracts the five feature-flag values for the matched entry.
     * @param[in] code  The 5-character variant code to locate.
     * @return  DictionaryEntry with found == true and populated fields on match;
     *          found == false when no match exists.
     */
    DictionaryEntry FindEntry(const std::string& code) const noexcept
    {
        DictionaryEntry entry{};

        // Locate the "code" key whose value matches the requested variant code.
        const std::string searchToken{"\"code\""};
        std::size_t       searchPos{0U};

        while (searchPos < jsonContent.size())
        {
            const std::size_t codeKeyPos{jsonContent.find(searchToken, searchPos)};
            if (codeKeyPos == std::string::npos)
            {
                break;
            }

            // Advance past the key to find the colon and then the value.
            const std::size_t colonPos{jsonContent.find(':', codeKeyPos + searchToken.size())};
            if (colonPos == std::string::npos)
            {
                break;
            }

            const std::size_t openQuote{jsonContent.find('"', colonPos + 1U)};
            if (openQuote == std::string::npos)
            {
                break;
            }

            const std::size_t closeQuote{jsonContent.find('"', openQuote + 1U)};
            if (closeQuote == std::string::npos)
            {
                break;
            }

            const std::string foundCode=jsonContent.substr(openQuote + 1U, closeQuote - openQuote - 1U);

            if (foundCode == code)
            {
                // Helper lambda: extract the string value for a given JSON key
                // within the object block that starts at codeKeyPos.
                auto extractValue = [&](const std::string& key) -> std::string
                {
                    const std::string keyToken{"\"" + key + "\""};
                    const std::size_t keyPos{jsonContent.find(keyToken, codeKeyPos)};
                    if (keyPos == std::string::npos)
                    {
                        return std::string{};
                    }
                    const std::size_t kColon{jsonContent.find(':', keyPos + keyToken.size())};
                    if (kColon == std::string::npos)
                    {
                        return std::string{};
                    }
                    const std::size_t kOpen{jsonContent.find('"', kColon + 1U)};
                    if (kOpen == std::string::npos)
                    {
                        return std::string{};
                    }
                    const std::size_t kClose{jsonContent.find('"', kOpen + 1U)};
                    if (kClose == std::string::npos)
                    {
                        return std::string{};
                    }
                    return jsonContent.substr(kOpen + 1U, kClose - kOpen - 1U);
                };

                entry.found                        = true;
                entry.regularProbeValue            = extractValue("regularProbeValue");
                entry.eventProbeValue              = extractValue("eventProbeValue");
                entry.eventProbeWithoutPictureValue = extractValue("eventProbeWithoutPictureValue");
                entry.gedrValue                    = extractValue("gedrValue");
                entry.gedrWithoutPictureValue      = extractValue("gedrWithoutPictureValue");
                return entry;
            }

            searchPos = closeQuote + 1U;
        }

        return entry;
    }
};

/**
 * @brief   Loads the variant dictionary JSON file from the given filesystem path.
 * @details Opens the file at @p path using std::ifstream, reads the entire content
 *          into a string, and returns a DictionaryLoadResult.  No dynamic memory
 *          beyond std::string internal storage is used.
 * @param[in] path  Absolute filesystem path to variant_table.json.
 * @return  DictionaryLoadResult with success == true and populated jsonContent on
 *          success; success == false when the file cannot be opened or is empty.
 */
DictionaryLoadResult LoadDictionary(const std::string& path) noexcept
{
    DictionaryLoadResult result{};

    std::ifstream fileStream{path};
    if (!fileStream.is_open())
    {
        result.success = false;
        return result;
    }

    std::ostringstream buffer{};
    buffer << fileStream.rdbuf();
    result.jsonContent = buffer.str();

    if (result.jsonContent.empty())
    {
        result.success = false;
        return result;
    }

    result.success = true;
    return result;
}

}  // anonymous namespace

// ---------------------------------------------------------------------------
// namespace probe — class method implementations
// ---------------------------------------------------------------------------

/// @namespace probe
/// @brief Contains all components of the probe application.
namespace probe {

// ============================================================
// PV-001 : ProbeCommVariant — Constructor
// ============================================================

/**
 * @brief   Constructs the variant configuration manager with safe default values.
 * @details Initializes all internal state to deterministic defaults. All boolean
 *          feature flags are set to false. The variant code is set to the compile-time
 *          default kDefaultVariantCode_. No shared memory access or file I/O is
 *          performed; those operations are deferred to ReadVariantCode() and
 *          SetVariant() called by ProbeApp during startup sequencing.
 *
 * @pre     None. The object may be constructed at any point before startup sequencing.
 * @post    All boolean feature flags are false. variantCode_ equals kDefaultVariantCode_.
 *          variantReadSuccess_ is false.
 *
 * @throws  None. This constructor is guaranteed not to throw.
 *
 * @note    Called by: ProbeApp during application initialization.
 * @note    MISRA C++:2008 compliant — all members initialized at declaration.
 *
 * @requirements SWR-REQ-01-03-001;SWR-REQ-03-14-001
 * @rationale Deferred I/O from constructor prevents blocking during object graph
 *            construction and simplifies unit testing.
 */
ProbeCommVariant::ProbeCommVariant() noexcept
    : defaultVariantCode_{kDefaultVariantCode_},
      variantReadSuccess_{false},
      regularProbeEnabled_{false},
      eventProbeEnabled_{false},
      eventProbeWithoutPictureEnabled_{false},
      gedrEnabled_{false},
      gedrWithoutPictureEnabled_{false},
      daqTransmissionEnabled_{false},
      variantDictionaryPath_{kVariantDictionaryPath_}
{
    // All members are explicitly initialised above via the member-initialiser list.
    // No external service interaction is performed during construction.
}

// ============================================================
// PV-002 : ~ProbeCommVariant — Destructor
// ============================================================

/**
 * @brief   Destroys the variant configuration manager and releases all resources.
 * @details Performs orderly cleanup of all resources held by the variant manager.
 *          All std::string members (variantCode_, defaultVariantCode_,
 *          variantDictionaryPath_) are released by standard C++ RAII semantics as
 *          they go out of scope. All boolean primitive members are automatically
 *          released. No external service calls or I/O operations are performed
 *          during destruction. Destruction completes deterministically within
 *          bounded execution time.
 *
 * @pre     The object must have been fully constructed.
 * @post    All resources owned by this instance are released.
 *
 * @throws  None. The destructor is guaranteed not to throw.
 *
 * @note    Called by: ProbeApp during application shutdown.
 * @requirements SWR-REQ-01-03-001;SWR-REQ-03-14-001
 */
ProbeCommVariant::~ProbeCommVariant() noexcept
{
    // All std::string members are automatically released by RAII:
    //   variantCode_, defaultVariantCode_, variantDictionaryPath_ go out of scope.
    // All boolean flags are primitive types; no explicit release is needed:
    //   regularProbeEnabled_, eventProbeEnabled_, eventProbeWithoutPictureEnabled_,
    //   gedrEnabled_, gedrWithoutPictureEnabled_, daqTransmissionEnabled_,
    //   variantReadSuccess_ are released automatically.
    // No external service interaction during destruction.
    // Destruction completes deterministically.
}

// ============================================================
// PV-003 : ReadVariantCode
// ============================================================

/**
 * @brief   Reads the 5-byte variant code from shared memory during initialization.
 * @details Calls SharedMemory_VariantCode_Read() (the concrete abstraction over
 *          Icmem_ReadVariantCode) and stores the result in readResult.  If
 *          readResult.success is true, variantCode_ is assigned readResult.value
 *          and variantReadSuccess_ is set to true.  If readResult.success is false,
 *          variantCode_ is assigned defaultVariantCode_, variantReadSuccess_ is set
 *          to false, and an error message is written to std::cerr.  SetVariant() is
 *          On shared-memory failure or failed dictionary match, ApplyDefaultVariantCode()
 *          is used; otherwise ApplyVariantFeatureFlags() applies the dictionary.  The
 *          resolved variantCode_ is returned to the caller.
 *
 * @return  std::string containing the resolved variant code (either read from shared
 *          memory or the compile-time default). Always a non-empty string of exactly
 *          kVariantCodeLength_ characters.
 *
 * @retval  kDefaultVariantCode_  Returned when shared memory read fails or returns
 *                                an invalid/empty result.
 * @retval  <variant_string>      The 5-character variant code successfully read from
 *                                shared memory.
 *
 * @pre     The SharedMem component must be initialized before this function is called.
 *          This function is intended to be called once during startup sequencing.
 * @post    variantCode_ contains the resolved variant code.
 *          variantReadSuccess_ reflects whether shared memory was read successfully.
 *
 * @throws  None. All error conditions are handled internally with fallback logic.
 *
 * @note    Called by: ProbeApp. Call condition: Startup.
 * @note    Provides interface: SharedMemory_VariantCode.
 * @warning Do not call this function after startup sequencing is complete.
 *
 * @requirements SWR-REQ-01-03-001;SWR-REQ-03-14-001
 * @rationale Fallback to default variant prevents a hard failure when shared memory
 *            is temporarily unavailable during early startup, improving system
 *            robustness per ISO 26262 ASIL-B fault tolerance requirements.
 * @see     SetVariant()
 */
std::string ProbeCommVariant::ReadVariantCodeFromSharedMemory()
{
    const SharedMemReadResult readResult{SharedMemory_VariantCode_Read()};

    if (readResult.success == true)
    {
        variantCode_        = readResult.value;
        variantReadSuccess_ = true;
    }
    else
    {
        variantCode_        = defaultVariantCode_;
        variantReadSuccess_ = false;
        std::cerr << "[ERROR] ReadVariantCode: shared memory read failed; applying default variant code";
    }

    return variantCode_;
}

void ProbeCommVariant::ApplyDefaultVariantCode() noexcept
{
    variantCode_        = defaultVariantCode_;
    variantReadSuccess_ = false;
    SetVariant(variantCode_);
}

bool ProbeCommVariant::ApplyVariantFeatureFlags() noexcept
{
    SetVariant(variantCode_);
    return variantDictionaryMatched_;
}

std::string ProbeCommVariant::ReadVariantCode()
{
    static_cast<void>(ReadVariantCodeFromSharedMemory());

    if (variantReadSuccess_ == false)
    {
        ApplyDefaultVariantCode();
    }
    else
    {
        if (ApplyVariantFeatureFlags() == false)
        {
            ApplyDefaultVariantCode();
        }
    }

    return variantCode_;
}

// ============================================================
// PV-004 : SetVariant
// ============================================================

/**
 * @brief   Enables or disables collection features based on the variant code matched
 *          against the variant dictionary.
 * @details Loads the variant dictionary from variantDictionaryPath_ via LoadDictionary().
 *          On load failure, calls HandleMissingVariantCode() and returns.  On success,
 *          calls dictionaryLoadResult.FindEntry(code) to locate the matching entry.
 *          If no entry is found, calls HandleMissingVariantCode() and returns.  When
 *          a match is found, each feature flag is set to true if the corresponding
 *          dictionary value equals "A", otherwise false.  daqTransmissionEnabled_ is
 *          set to true.  A diagnostic message is written to std::cout.
 *
 * @param[in] code  The variant code string to look up in the variant dictionary.
 *                  Must be a non-empty string of exactly kVariantCodeLength_ characters.
 *                  Valid range: printable ASCII characters, length == kVariantCodeLength_.
 *
 * @pre     ReadVariantCode() must have been called prior to this function so that
 *          variantCode_ is populated. The variant dictionary file must be accessible
 *          at variantDictionaryPath_.
 * @post    All boolean feature flags reflect the variant entry matched by @p code,
 *          or all flags are false if no match was found.
 *
 * @throws  None. File I/O errors and parse failures are handled internally.
 *
 * @note    Called by: ProbeApp. Call condition: Startup.
 * @warning Calling this function with an empty string will disable all transmission.
 *
 * @requirements SWR-REQ-01-03-002;SWR-REQ-03-14-002
 * @rationale Dictionary-based variant control allows one binary to support multiple
 *            vehicle configurations without recompilation, reducing integration risk.
 * @see     ReadVariantCode(), HandleMissingVariantCode(), DisableAllTransmissionOnInvalidVariant()
 */
void ProbeCommVariant::SetVariant(const std::string& code)
{
    variantDictionaryMatched_ = false;

    // Input validation: empty or oversized code causes immediate fail-safe.
    if (code.empty() || (code.size() != kVariantCodeLength_))
    {
        std::cerr << "[ERROR] SetVariant: invalid code length; expected "
                  << kVariantCodeLength_ << " characters, got " << code.size() << "";
        HandleMissingVariantCode();
        return;
    }

    // Load the variant dictionary from configured path.
    const DictionaryLoadResult dictionaryLoadResult{LoadDictionary(variantDictionaryPath_)};

    if (dictionaryLoadResult.success == false)
    {
        // Dictionary file missing or parse error.
        std::cerr << "[ERROR] SetVariant: variant dictionary load failed at path: "
                  << variantDictionaryPath_ << "";
        HandleMissingVariantCode();
        return;
    }

    // Search for the variant code entry in the dictionary.
    const DictionaryEntry dictionaryEntry{dictionaryLoadResult.FindEntry(code)};

    if (dictionaryEntry.found == false)
    {
        // Variant code not present in dictionary.
        std::cerr << "[ERROR] SetVariant: variant code not found in dictionary: " << code << "";
        HandleMissingVariantCode();
        return;
    }

    // Apply feature flags based on dictionary entry values.
    // Activation value is "A"; all others mean disabled.
    if (dictionaryEntry.regularProbeValue == "A")
    {
        regularProbeEnabled_ = true;
    }
    else
    {
        regularProbeEnabled_ = false;
    }

    if (dictionaryEntry.eventProbeValue == "A")
    {
        eventProbeEnabled_ = true;
    }
    else
    {
        eventProbeEnabled_ = false;
    }

    if (dictionaryEntry.eventProbeWithoutPictureValue == "A")
    {
        eventProbeWithoutPictureEnabled_ = true;
    }
    else
    {
        eventProbeWithoutPictureEnabled_ = false;
    }

    if (dictionaryEntry.gedrValue == "A")
    {
        gedrEnabled_ = true;
    }
    else
    {
        gedrEnabled_ = false;
    }

    if (dictionaryEntry.gedrWithoutPictureValue == "A")
    {
        gedrWithoutPictureEnabled_ = true;
    }
    else
    {
        gedrWithoutPictureEnabled_ = false;
    }

    // Enable DAQ transmission since variant code was resolved.
    daqTransmissionEnabled_ = true;
    variantDictionaryMatched_ = true;

    // Log all applied flag states for diagnostics.
    std::cout << "[INFO] SetVariant: flags applied for code: " << code << "";
}

// ============================================================
// PV-005 : CheckRegularProbeEnabled
// ============================================================

/**
 * @brief   Returns whether regular probe data collection is enabled based on the active variant.
 * @details Provides a read-only query of the regularProbeEnabled_ flag, which is set
 *          by SetVariant() after matching the variant code against the dictionary.
 *          No state modification occurs. Execution is bounded and deterministic in O(1).
 *
 * @return  bool indicating whether regular probe data collection is active.
 *
 * @retval  true   Regular probe data collection is enabled for the active variant.
 * @retval  false  Regular probe data collection is disabled, either because the
 *                 variant does not support it or because SetVariant() has not been
 *                 called successfully.
 *
 * @pre     SetVariant() must have been called during startup sequencing.
 * @post    Internal state is not modified.
 *
 * @throws  None. This function is guaranteed not to throw.
 *
 * @note    Called by: ProbeApp. Call condition: On_Request.
 *
 * @requirements SWR-REQ-01-03-002;SWR-REQ-03-14-002
 * @see     SetVariant(), CheckEventProbeEnabled()
 */
bool ProbeCommVariant::CheckRegularProbeEnabled() const noexcept
{
    // Return the current state of the regular probe feature flag.
    return regularProbeEnabled_;
}

// ============================================================
// PV-006 : CheckEventProbeEnabled
// ============================================================

/**
 * @brief   Returns whether event probe data collection is enabled based on the active variant.
 * @details Provides a read-only query of the eventProbeEnabled_ flag, which is set
 *          by SetVariant() after matching the variant code against the dictionary.
 *          No state modification occurs. Execution is bounded and deterministic in O(1).
 *
 * @return  bool indicating whether event probe data collection is active.
 *
 * @retval  true   Event probe data collection (with picture) is enabled for the active variant.
 * @retval  false  Event probe data collection is disabled, either because the variant
 *                 does not support it or because SetVariant() has not been called successfully.
 *
 * @pre     SetVariant() must have been called during startup sequencing.
 * @post    Internal state is not modified.
 *
 * @throws  None. This function is guaranteed not to throw.
 *
 * @note    Called by: ProbeApp. Call condition: On_Request.
 *
 * @requirements SWR-REQ-01-03-002;SWR-REQ-03-14-002
 * @see     SetVariant(), CheckEventProbeWithoutPictureEnabled()
 */
bool ProbeCommVariant::CheckEventProbeEnabled() const noexcept
{
    // Return the current state of the event probe feature flag.
    return eventProbeEnabled_;
}

// ============================================================
// PV-007 : CheckEventProbeWithoutPictureEnabled
// ============================================================

/**
 * @brief   Returns whether event probe without picture is enabled based on the active variant.
 * @details Provides a read-only query of the eventProbeWithoutPictureEnabled_ flag.
 *          No state modification occurs. Execution is deterministic and bounded in O(1).
 *
 * @return  bool indicating whether event probe without picture is active.
 *
 * @retval  true   Event probe without picture is enabled for the active variant.
 * @retval  false  Event probe without picture is disabled for the active variant.
 *
 * @pre     SetVariant() must have been called during startup sequencing.
 * @post    Internal state is not modified.
 *
 * @throws  None. This function is guaranteed not to throw.
 *
 * @note    Called by: ProbeApp. Call condition: On_Request.
 *
 * @requirements SWR-REQ-01-03-002;SWR-REQ-03-14-002
 * @see     SetVariant(), CheckEventProbeEnabled()
 */
bool ProbeCommVariant::CheckEventProbeWithoutPictureEnabled() const noexcept
{
    // Return the current state of the event probe without picture feature flag.
    return eventProbeWithoutPictureEnabled_;
}

// ============================================================
// PV-008 : CheckGedrEnabled
// ============================================================

/**
 * @brief   Returns whether GEDR data collection is enabled based on the active variant.
 * @details Provides a read-only query of the gedrEnabled_ flag, which is set by
 *          SetVariant() after matching the variant code against the dictionary.
 *          No state modification occurs. Execution is deterministic and bounded in O(1).
 *
 * @return  bool indicating whether GEDR data collection (with picture) is active.
 *
 * @retval  true   GEDR data collection with picture is enabled for the active variant.
 * @retval  false  GEDR data collection is disabled for the active variant.
 *
 * @pre     SetVariant() must have been called during startup sequencing.
 * @post    Internal state is not modified.
 *
 * @throws  None. This function is guaranteed not to throw.
 *
 * @note    Called by: ProbeApp. Call condition: On_Request.
 *
 * @requirements SWR-REQ-01-03-002;SWR-REQ-03-14-002
 * @see     SetVariant(), CheckGedrWithoutPictureEnabled()
 */
bool ProbeCommVariant::CheckGedrEnabled() const noexcept
{
    // Return the current state of the GEDR feature flag.
    return gedrEnabled_;
}

}  // namespace probe

/// @namespace probe
/// @brief Contains all components of the probe application.
namespace probe {

/**
 * @brief   Returns whether GEDR without picture is enabled based on the active variant.
 * @details Provides a read-only query of the gedrWithoutPictureEnabled_ flag.
 *          This flag distinguishes between full GEDR mode (with camera image frames)
 *          and a reduced GEDR mode that writes signal data only, without image payloads.
 *          Variants without camera capability may still support GEDR signal recording
 *          via this mode. The function reads the flag and returns its value without
 *          modifying any state. Execution is deterministic and bounded in O(1).
 *
 * @return  bool indicating whether GEDR without picture is active.
 *
 * @retval  true   GEDR without picture is enabled for the active variant.
 * @retval  false  GEDR without picture is disabled for the active variant, or
 *                 SetVariant() has not been called with a valid matching code.
 *
 * @pre     SetVariant() must have been called during startup sequencing.
 * @post    Internal state is not modified.
 *
 * @throws  None. This function is guaranteed not to throw.
 *
 * @note    Called by: ProbeApp. Call condition: On_Request.
 * @note    This function is safe to call from any point after startup sequencing.
 * @note    MISRA C++:2008 compliant — no side effects, const-qualified member function.
 *
 * @requirements SWR-REQ-01-03-002;SWR-REQ-03-14-002
 * @see     SetVariant(), CheckGedrEnabled()
 */
bool ProbeCommVariant::CheckGedrWithoutPictureEnabled() const noexcept
{
    return gedrWithoutPictureEnabled_;
}

/**
 * @brief   Returns whether DAQ transmission is enabled based on the active variant.
 * @details Provides a read-only query of the daqTransmissionEnabled_ flag. DAQ
 *          transmission covers both regular (continual) and event-based data uploads
 *          to the DAQ service on the Core ECU via SOME/IP. This flag is set to false
 *          when the variant code is not found in the dictionary (per SWR-REQ-01-03-003),
 *          ensuring that no data is transmitted to DAQ when the vehicle configuration
 *          is unrecognised. The function reads the flag and returns its value without
 *          modifying any state. Execution is deterministic and bounded in O(1).
 *          When this flag is false, the calling context must suppress all outbound
 *          messages to DAQ to prevent transmission to an unconfigured destination.
 *
 * @return  bool indicating whether DAQ transmission is permitted for the active variant.
 *
 * @retval  true   DAQ transmission is enabled for the active variant.
 * @retval  false  DAQ transmission is disabled — either the variant code was not found
 *                 in the dictionary, or SetVariant() has not been called successfully.
 *
 * @pre     SetVariant() must have been called during startup sequencing.
 * @post    Internal state is not modified.
 *
 * @throws  None. This function is guaranteed not to throw.
 *
 * @note    Called by: ProbeApp. Call condition: On_Request.
 * @note    This function is safe to call from any point after startup sequencing.
 * @warning Per SWR-REQ-01-03-003, this flag is explicitly false when the variant
 *          code is absent from the dictionary. Do not bypass this check.
 * @note    MISRA C++:2008 compliant — no side effects, const-qualified member function.
 *
 * @requirements SWR-REQ-01-03-002;SWR-REQ-01-03-003;SWR-REQ-03-14-002
 * @see     SetVariant(), HandleMissingVariantCode(), DisableAllTransmissionOnInvalidVariant()
 */
bool ProbeCommVariant::CheckDaqTransmissionEnabled() const noexcept
{
    return daqTransmissionEnabled_;
}

uint16_t ProbeCommVariant::REQUEST_BDP_UPLOAD_REQ_RES(uint16_t clientId,
                                                      uint32_t eventValue,
                                                      uint32_t dataSize,
                                                      uint32_t requestNum) noexcept
{
    (void)clientId;
    (void)eventValue;
    (void)dataSize;
    (void)requestNum;
    return 0U;
}

uint16_t ProbeCommVariant::TRANSMIT_BDP_REQ_RES(uint16_t clientId,
                                                uint32_t requestNum,
                                                const std::vector<uint8_t>& contents) noexcept
{
    (void)clientId;
    (void)requestNum;
    (void)contents;
    return 0U;
}

/**
 * @brief   Logs an error and prevents data transmission when the variant code is not found in the dictionary.
 * @details Called internally by SetVariant() when the provided variant code string
 *          does not match any entry in the variant dictionary (variant_table.json).
 *          This function logs the unrecognised variant code and the current
 *          variantReadSuccess_ state to std::cerr to provide full diagnostic context,
 *          then delegates to DisableAllTransmissionOnInvalidVariant() to set all
 *          feature flags to false, ensuring no data is transmitted to DAQ or GEDR
 *          for an unrecognised vehicle configuration. This implements the fail-safe
 *          behavior required by SWR-REQ-01-03-003. After this call, no data collection
 *          or transmission to DAQ or GEDR is possible until a system restart provides
 *          a valid variant. Execution is deterministic and bounded.
 *
 * @pre     variantCode_ must contain the unrecognised code that triggered this call.
 * @post    All boolean feature flags are false. daqTransmissionEnabled_ is false.
 *
 * @throws  None. This function is guaranteed not to throw.
 *
 * @note    Called by: ProbeCommVariant (internal). Call condition: Startup.
 * @note    This is a private safety-critical function. Its behavior must not be
 *          altered without a corresponding change to the safety analysis.
 * @warning Do not call this function directly from outside the class. It is invoked
 *          exclusively by SetVariant() as part of the missing-variant handling path.
 * @note    MISRA C++:2008 compliant — no dynamic allocation, no recursion,
 *          all members explicitly modified via delegated call.
 *
 * @requirements SWR-REQ-01-03-003;SWR-REQ-03-14-003
 * @rationale Centralising the missing-variant error path ensures consistent
 *            fail-safe behavior and simplifies safety analysis traceability.
 * @see     DisableAllTransmissionOnInvalidVariant(), SetVariant()
 */
void ProbeCommVariant::HandleMissingVariantCode() noexcept
{
    std::cerr << "HandleMissingVariantCode: variant code not resolved: "
              << variantCode_
              << " readSuccess: "
              << variantReadSuccess_
              << "";

    DisableAllTransmissionOnInvalidVariant();
}

/**
 * @brief   Disables all data sending to DAQ and GEDR when the variant is invalid.
 * @details Sets all boolean feature flags to false:
 *          regularProbeEnabled_, eventProbeEnabled_, eventProbeWithoutPictureEnabled_,
 *          gedrEnabled_, gedrWithoutPictureEnabled_, and daqTransmissionEnabled_.
 *          This function implements the fail-safe transmission lockout required when
 *          the vehicle variant code cannot be resolved to a known configuration.
 *          It is called exclusively by HandleMissingVariantCode() and ensures that
 *          no data is transmitted to any downstream system (DAQ, GEDR) in an
 *          undefined variant state. All flag assignments are sequential, unconditional,
 *          and deterministic. After this function returns, all Check*Enabled() query
 *          functions will return false, preventing any data flow. A LOG_INFO diagnostic
 *          message is emitted to std::cout to record the disablement for traceability.
 *          Execution is deterministic and bounded in O(1).
 *
 * @pre     None. This function may be called at any point during startup sequencing.
 * @post    All boolean feature flags are false. No transmission will be initiated
 *          by any Check*Enabled() query until SetVariant() is called with a valid code.
 *
 * @throws  None. This function is guaranteed not to throw.
 *
 * @note    Called by: ProbeCommVariant (internal via HandleMissingVariantCode()).
 *          Call condition: Startup.
 * @note    This is a private safety-critical function implementing ASIL-B fail-safe
 *          behavior. All flag assignments are explicit and deterministic.
 * @warning This function unconditionally disables all transmission. Ensure it is
 *          only invoked on confirmed invalid variant conditions.
 * @note    MISRA C++:2008 compliant — no dynamic allocation, no recursion,
 *          no branches, all members explicitly assigned.
 *
 * @requirements SWR-REQ-01-03-003;SWR-REQ-03-14-003
 * @rationale A single dedicated function for disabling all transmission flags
 *            provides a single point of control for the fail-safe path, reducing
 *            the risk of partial flag updates and simplifying code review.
 * @see     HandleMissingVariantCode()
 */
void ProbeCommVariant::DisableAllTransmissionOnInvalidVariant() noexcept
{
    regularProbeEnabled_                = false;
    eventProbeEnabled_                  = false;
    eventProbeWithoutPictureEnabled_    = false;
    gedrEnabled_                        = false;
    gedrWithoutPictureEnabled_          = false;
    daqTransmissionEnabled_             = false;

    std::cout << "DisableAllTransmissionOnInvalidVariant: all transmission flags disabled";
}

}  // namespace probe