/**
 * @file   ProbeApp.cpp
 * @brief  Implementation of ProbeApp component.
 * @details Portable C++ implementation generated by
 *          the Code Generation Pipeline.
 *          Uses runtime::IRuntime for all platform-dependent behavior.
 * @author  Engineering Team
 * @version 1.0.0
 * @copyright Copyright (c) 2024 Company. All rights reserved.
 */
#include "CanConsumer/CanConsumer.hpp"
#include "ProbeCommVariant/ProbeCommVariant.hpp"
#include "ProbeApp/ProbeApp.hpp"
#include <algorithm>
#include <atomic>
#include <chrono>
#include <cstdint>
#include <deque>
#include <iostream>
#include <mutex>
#include <stdexcept>
#include <thread>
#include <vector>

/// @namespace probe
/// @brief Contains all components of the probe application.
namespace probe {

// ============================================================
// Internal helper: monotonic timestamp in seconds (uint32_t)
// ============================================================

/**
 * @brief   Returns the current monotonic clock time in whole seconds.
 * @details Uses std::chrono::steady_clock to obtain a monotonic timestamp.
 *          The epoch is the steady_clock epoch (application-relative).
 * @return  uint32_t  Current monotonic time in seconds.
 * @throws  None.
 * @note    Internal helper — not exposed in the public interface.
 */
static uint32_t GetMonotonicTimeSec() noexcept
{
    const auto now{std::chrono::steady_clock::now()};
    const auto duration{now.time_since_epoch()};
    const uint64_t seconds{
        static_cast<uint64_t>(
            std::chrono::duration_cast<std::chrono::seconds>(duration).count())};
    return static_cast<uint32_t>(seconds & static_cast<uint64_t>(0xFFFFFFFFU));
}

/**
 * @brief   Returns the current monotonic clock time in whole milliseconds.
 * @details Uses std::chrono::steady_clock to obtain a monotonic timestamp.
 * @return  uint64_t  Current monotonic time in milliseconds.
 * @throws  None.
 * @note    Internal helper — not exposed in the public interface.
 */
static uint64_t GetMonotonicTimeMs() noexcept
{
    const auto now{std::chrono::steady_clock::now()};
    const auto duration{now.time_since_epoch()};
    return static_cast<uint64_t>(
        std::chrono::duration_cast<std::chrono::milliseconds>(duration).count());
}

// ============================================================
// Maximum buffer capacity constants
// ============================================================

/**
 * @brief   Maximum number of entries in the 100 ms CAN ring buffer.
 * @details Derived as (kSampleRate1000Ms / kSampleRate100Ms) * kDefaultPastDataRetentionCount
 *          = (1000 / 100) * 10 = 100 entries.
 */
static constexpr uint32_t kMaxBuffer100Ms{
    (ProbeApp::kSampleRate1000Ms / ProbeApp::kSampleRate100Ms) *
    ProbeApp::kDefaultPastDataRetentionCount};

/**
 * @brief   Maximum number of entries in the 1000 ms CAN ring buffer.
 * @details Equals kDefaultPastDataRetentionCount = 10 entries.
 */
static constexpr uint32_t kMaxBuffer1000Ms{ProbeApp::kDefaultPastDataRetentionCount};

// ============================================================
// ProbeApp Constructor
// ============================================================

/**
 * @brief   Constructs ProbeApp with references to communication, variant, and CAN consumer.
 * @details Initializes all internal RAM buffers, validates all dependency pointers, reads
 *          and applies variant configuration, and sets all lifecycle flags to their safe
 *          default states. Throws std::runtime_error if any mandatory dependency is nullptr.
 *          Throws std::invalid_argument if variant configuration returns an inconsistent state.
 *
 *          Initialization sequence:
 *          1. Validate probeCommVariant and canConsumer — fatal if nullptr.
 *          2. Assign all dependency pointers.
 *          3. Initialize all lifecycle flags and counters to safe defaults.
 *          4. Clear all buffer containers and reserve capacity.
 *          5. Apply variant configuration via probeCommVariant.
 *          6. Warn (non-fatal) if probeComm is nullptr.
 *
 * @param[in] comm     Non-owning pointer to the ProbeComm communication handler.
 *                     Must not be nullptr. Lifetime must exceed ProbeApp lifetime.
 * @param[in] variant  Non-owning pointer to the ProbeCommVariant configuration manager.
 *                     Must not be nullptr. Lifetime must exceed ProbeApp lifetime.
 * @param[in] canCons  Non-owning pointer to the CanConsumer shared-memory signal reader.
 *                     Must not be nullptr. Lifetime must exceed ProbeApp lifetime.
 * @throws  std::runtime_error    If variant or canCons pointer is nullptr.
 * @throws  std::invalid_argument If variant configuration returns an inconsistent state.
 * @pre     All three pointer arguments must be valid, fully constructed objects.
 * @post    All internal buffers are allocated and zero-initialized.
 *          isRunning_ == false, shutdownRequested_ == false, collectionStarted_ == false.
 *          msCounter_ == 0.
 * @note    Called by: Main.
 * @requirements SWR-REQ-01-01-002;SWR-REQ-01-01-003;SWR-REQ-01-02-001
 * @rationale Dependency injection via constructor parameters enables unit testing
 *            and avoids hidden global state. Non-owning raw pointers are used here
 *            because lifetime is strictly controlled by Main (MISRA M1 observer pattern).
 * @see     ProbeComm, ProbeCommVariant, CanConsumer
 */
ProbeApp::ProbeApp(ProbeComm* comm,
                   ProbeCommVariant* variant,
                   CanConsumer* canCons)
    : probeComm_{nullptr}
    , probeCommVariant_{nullptr}
    , canConsumer_{nullptr}
    // , canBuffer100ms_null
    // , canBuffer1000ms_null
    // , logDataSetBuffer_null
    // , steadyStateDataBuffer100ms_null
    // , steadyStateDataBuffer1000ms_null
    // , eventSendingBuffer_null
    // , imageDataBuffer_null
    , msCounter_{0U}
    , startupTimeSec_{0U}
    , pastDataRetentionCount_{kDefaultPastDataRetentionCount}
    , isRunning_{false}
    , isDaqCommEstablished_{false}
    , shutdownRequested_{false}
    , collectionStarted_{false}
{
    // Validate critical dependency: variant manager
    if (variant == nullptr)
    {
        throw std::runtime_error(
            "ProbeApp: Fatal initialization error — probeCommVariant pointer is nullptr.");
    }

    // Validate critical dependency: CAN consumer
    if (canCons == nullptr)
    {
        throw std::runtime_error(
            "ProbeApp: Fatal initialization error — canConsumer pointer is nullptr.");
    }

    // Assign injected dependency references
    probeComm_        = comm;
    probeCommVariant_ = variant;
    canConsumer_      = canCons;

    // Initialize all boolean lifecycle flags to safe defaults
    isRunning_.store(false);
    isDaqCommEstablished_.store(false);
    shutdownRequested_.store(false);
    collectionStarted_.store(false);

    // Initialize counters to zero
    msCounter_      = 0U;
    startupTimeSec_ = 0U;

    // Set configurable parameter: past data retention depth
    pastDataRetentionCount_ = kDefaultPastDataRetentionCount;

    // Initialize all buffer containers to empty state
    canBuffer100ms_null.clear();
    canBuffer1000ms_null.clear();
    logDataSetBuffer_null.clear();
    steadyStateDataBuffer100ms_null.clear();
    steadyStateDataBuffer1000ms_null.clear();
    eventSendingBuffer_null.clear();
    imageDataBuffer_null.clear();

    // Reserve capacity to eliminate runtime allocation during cyclic execution
    steadyStateDataBuffer100ms_null.reserve(static_cast<std::size_t>(kMaxBuffer100Ms));
    steadyStateDataBuffer1000ms_null.reserve(static_cast<std::size_t>(kMaxBuffer1000Ms));
    eventSendingBuffer_null.reserve(static_cast<std::size_t>(kDefaultPastDataRetentionCount));

    // Apply variant configuration: read shared memory, then default or dictionary path
    static_cast<void>(probeCommVariant_->ReadVariantCodeFromSharedMemory());
    if (probeCommVariant_->IsVariantReadSuccessful() == false)
    {
        probeCommVariant_->ApplyDefaultVariantCode();
    }
    else
    {
        if (probeCommVariant_->ApplyVariantFeatureFlags() == false)
        {
            probeCommVariant_->ApplyDefaultVariantCode();
        }
    }

    // Validate communication handler availability (non-fatal at construction)
    if (probeComm_ == nullptr)
    {
        // Non-fatal: communication will be established in HandleInitialize
        std::cerr << "ProbeApp: Warning — probeComm pointer is nullptr at construction. "
                     "Communication will be established in HandleInitialize.";
    }
}

// ============================================================
// ProbeApp Destructor
// ============================================================

/**
 * @brief   Destructor. Releases no heap resources (RAII — all members are value types).
 * @details Ensures that isRunning_ is set to false before destruction. Does not call
 *          HandleShutdown() — the caller must invoke HandleShutdown() or HandleTerminate()
 *          before destroying this object.
 * @throws  None.
 * @note    noexcept — destructor must never throw per C++ standard.
 */
ProbeApp::~ProbeApp() noexcept
{
    isRunning_.store(false);
}

// ============================================================
// HandleInitialize
// ============================================================

/**
 * @brief   Starts ProbeApp operation after ADAS ECU startup and initiates SOME/IP
 *          communication with DAQ.
 * @details Invoked once by Main after the Adaptive AUTOSAR execution state has been
 *          reported as kRunning. Reads and applies variant configuration, sets isRunning_
 *          to true, records startupTimeSec_, and initiates SOME/IP service discovery and
 *          service offering via ProbeComm. isDaqCommEstablished_ remains false until the
 *          session is confirmed asynchronously within the Run loop.
 *
 *          Initialization sequence:
 *          1. Read variant code; apply default on failure.
 *          2. Apply variant feature flags; apply default if flag application fails.
 *          3. Set isRunning_ = true.
 *          4. Capture startupTimeSec_ from monotonic clock.
 *          5. Initiate SOME/IP service discovery via ProbeComm FindService* calls.
 *          6. Offer SOME/IP services via ProbeComm OfferService* calls.
 *          7. isDaqCommEstablished_ remains false (updated on service found callback).
 *
 * @throws  std::runtime_error  If probeComm_ is nullptr (defensive check).
 * @pre     Constructor has completed successfully. isRunning_ == false.
 * @post    isRunning_ == true. SOME/IP service discovery has been initiated.
 *          startupTimeSec_ holds the monotonic timestamp of initialization.
 * @note    Requirements: SWR-REQ-01-10-001, SWR-REQ-01-10-002, SWR-REQ-01-03-001,
 *          SWR-REQ-03-16-001, SWR-REQ-03-16-002.
 * @warning Must be called exactly once before Run(). Calling twice results in
 *          undefined behavior (duplicate service registration).
 * @requirements SWR-REQ-01-10-001;SWR-REQ-01-10-002;SWR-REQ-01-03-001;SWR-REQ-03-16-001;SWR-REQ-03-16-002
 * @rationale Separating initialization from construction allows the Adaptive AUTOSAR
 *            framework to control the exact moment service discovery begins.
 * @see     ProbeComm::FindServiceDaqContinual, ProbeComm::OfferServiceProbeEventStt
 */
void ProbeApp::HandleInitialize()
{
    // Step 1: Read variant code and resolve dictionary (same sequencing as constructor)
    static_cast<void>(probeCommVariant_->ReadVariantCodeFromSharedMemory());
    if (probeCommVariant_->IsVariantReadSuccessful() == false)
    {
        probeCommVariant_->ApplyDefaultVariantCode();
    }
    else
    {
        if (probeCommVariant_->ApplyVariantFeatureFlags() == false)
        {
            probeCommVariant_->ApplyDefaultVariantCode();
        }
    }

    // Step 2: Mark application as running
    isRunning_.store(true);

    // Step 3: Capture startup reference timestamp
    startupTimeSec_ = GetMonotonicTimeSec();

    // Step 4: Initiate SOME/IP service discovery with DAQ
    // isDaqCommEstablished_ remains false until session confirmed in Run
    if (probeComm_ != nullptr)
    {
        probeComm_->FindServiceDaqContinual();
        probeComm_->FindServiceDaqDevEvent();
        probeComm_->FindServiceZatTrigger();
        probeComm_->FindServiceZatRegularUpload();
        probeComm_->FindServiceCameraImg();
        probeComm_->FindServiceCameraAghdf();
        probeComm_->FindServiceTsr2GCoreHdf();
        probeComm_->FindServiceTsr2Hdf();
        probeComm_->FindServiceHdfAp2CpBusOut();
        probeComm_->FindServiceHdfCp2ApBusOut();
        probeComm_->FindServiceSdmap();

        probeComm_->OfferServiceProbeEventStt();
        probeComm_->OfferServiceProbeTrigger();
    }
    else
    {
        // Non-fatal: Run loop will continue retrying discovery
        // isDaqCommEstablished_ remains false; data transmission suppressed
        std::cerr << "ProbeApp::HandleInitialize: probeComm_ is nullptr — "
                     "SOME/IP discovery deferred.";
    }

    // Step 5: HandleInitialize complete
    // isRunning_ = true, isDaqCommEstablished_ = false (pending confirmation)
    // startupTimeSec_ captures boot reference for 10-second delay check in Run
}

// ============================================================
// Run
// ============================================================

/**
 * @brief   Runs the cyclic data collection and transmission processing loop.
 * @details Called periodically from the 10 ms task context. On each invocation:
 *          1. Checks shutdownRequested_ — returns immediately if true.
 *          2. Checks collectionStarted_ via CheckCollectionStartDelay().
 *          3. If collection started: dispatches CollectSharedMemReadSignals(),
 *             StoreCanData100ms(), and StoreCanData1000ms() at appropriate boundaries.
 *          4. Increments and wraps msCounter_.
 *          5. Transmits steady-state data if DAQ session is confirmed.
 *          6. Attempts re-discovery if DAQ session is not confirmed.
 *          7. Enforces 100 ms cycle boundary via sleep.
 *
 *          All sub-rate scheduling is derived from msCounter_ modulo arithmetic.
 *          This function is non-blocking and must complete within the 10 ms task budget.
 *
 * @throws  None (all internal errors handled via explicit status checks).
 * @pre     HandleInitialize() has been called. isRunning_ == true.
 * @post    msCounter_ has been incremented. Buffers updated according to elapsed time.
 * @note    Requirements: SWR-REQ-01-001, SWR-REQ-01-002, SWR-REQ-01-005,
 *          SWR-REQ-01-06-001, SWR-REQ-01-10-003, SWR-REQ-03-16-003.
 * @warning Must not be called after HandleTerminate() or HandleShutdown().
 *          Must complete within 10 ms to avoid task overrun.
 * @requirements SWR-REQ-01-001;SWR-REQ-01-002;SWR-REQ-01-005;SWR-REQ-01-06-001;SWR-REQ-01-10-003;SWR-REQ-03-16-003
 * @rationale Single-entry cyclic design avoids thread synchronization overhead and
 *            ensures deterministic execution order per ISO 26262 ASIL-B requirements.
 * @see     CollectSharedMemReadSignals, BuildLogDataSetPerSecond, SendRegularData
 */
void ProbeApp::Run()
{
    // Enter cyclic execution loop; terminates on shutdown request
    while ((shutdownRequested_.load() == false) && (isRunning_.load() == true))
    {
        // Record cycle start time for period enforcement (milliseconds)
        const uint64_t cycleStartTime{GetMonotonicTimeMs()};

        // Step 1: Check if startup delay has elapsed and enable collection
        CheckCollectionStartDelay();

        // Step 2: Execute data collection if collection is enabled
        if (collectionStarted_.load() == true)
        {
            // Step 2a: Collect signals from shared memory at applicable rates
            CollectSharedMemReadSignals();

            // Step 2b: Store 100 ms rate data every cycle
            StoreCanData100ms();

            // Step 2c: Store 1000 ms rate data only at 1000 ms boundary
            if ((msCounter_ % 1000U) == 0U)
            {
                StoreCanData1000ms();
            }

            // Step 2d: Increment millisecond counter; reset at LCM boundary
            msCounter_ = msCounter_ + 100U;
            if (msCounter_ >= 1000U)
            {
                msCounter_ = 0U;
            }
        }
        // else: Startup delay not yet elapsed; skip collection and transmission

        // Step 3: Transmit steady-state data if DAQ session is confirmed
        if ((isDaqCommEstablished_.load() == true) && (collectionStarted_.load() == true))
        {
            SendRegularData();
        }
        else if (isDaqCommEstablished_.load() == false)
        {
            // Attempt to re-establish DAQ communication
            if (probeComm_ != nullptr)
            {
                probeComm_->FindServiceDaqContinual();
                // isDaqCommEstablished_ is set by service-found callback (async)
            }
            // No data transmitted while session not confirmed
        }
        else
        {
            // No-op: collection not yet started
        }

        // Step 4: Enforce 100 ms cycle boundary
        const uint64_t cycleElapsed{GetMonotonicTimeMs() - cycleStartTime};
        if (cycleElapsed < static_cast<uint64_t>(100U))
        {
            const uint64_t sleepMs{static_cast<uint64_t>(100U) - cycleElapsed};
            std::this_thread::sleep_for(std::chrono::milliseconds(sleepMs));
        }
        // If cycleElapsed >= 100, next cycle starts immediately
    }

    // Loop exited: shutdown or stop requested
    // Cleanup performed by HandleTerminate
}

// ============================================================
// HandleTerminate
// ============================================================

/**
 * @brief   Stops all data collection and transmission processing on termination request.
 * @details Sets shutdownRequested_ = true and isRunning_ = false. Invokes
 *          ClearAllTemporaryData() to purge all RAM buffers. If deletion fails,
 *          initiates a hard application stop via EnforceStopOnRamCleanupFailure().
 *
 *          Sequence:
 *          1. Set shutdownRequested_ = true.
 *          2. Set isRunning_ = false.
 *          3. Call ClearAllTemporaryData().
 *          4. If deletion fails, call EnforceStopOnRamCleanupFailure().
 *
 * @throws  None.
 * @pre     HandleInitialize() has been called previously.
 * @post    isRunning_ == false. shutdownRequested_ == true.
 *          No further data collection or transmission will occur.
 * @note    Requirements: SWR-REQ-01-09-001, SWR-REQ-03-13-001.
 * @warning After this call, no data transmission will occur. Buffers retain their
 *          last state until HandleShutdown() or destructor is called.
 * @requirements SWR-REQ-01-09-001;SWR-REQ-03-13-001
 * @rationale Separating termination (stop processing) from shutdown (purge data)
 *            allows the framework to distinguish graceful stop from emergency stop.
 * @see     HandleShutdown
 */
void ProbeApp::HandleTerminate()
{
    // Step 1: Signal the Run loop to stop on next cycle boundary
    shutdownRequested_.store(true);

    // Step 2: Mark application as no longer running
    isRunning_.store(false);

    // Step 3: Purge all RAM buffers including in-transit data
    ClearAllTemporaryData();

    // Step 4: Verify deletion success — ClearAllTemporaryData handles internal
    // consistency; if buffers are non-empty after clear, enforce hard stop
    {
        std::lock_guard<std::mutex> lock100ms(bufferMutex100ms_null);
        std::lock_guard<std::mutex> lock1000ms(bufferMutex1000ms_null);
        std::lock_guard<std::mutex> lockLog(logBufferMutex_null);

        const bool buffersEmpty{
            canBuffer100ms_null.empty() &&
            canBuffer1000ms_null.empty() &&
            logDataSetBuffer_null.empty() &&
            steadyStateDataBuffer100ms_null.empty() &&
            steadyStateDataBuffer1000ms_null.empty() &&
            eventSendingBuffer_null.empty() &&
            imageDataBuffer_null.empty()};

        if (!buffersEmpty)
        {
            // Deletion failed: residual data may contain personal information
            // Hard stop: prevent further operation in inconsistent state
            EnforceStopOnRamCleanupFailure();
        }
        // else: All temporary data deleted successfully; HandleTerminate completes normally
    }
}

// ============================================================
// HandleShutdown
// ============================================================

/**
 * @brief   Stops all processing and deletes all temporary data including mid-transmission
 *          data on ADAS ECU shutdown.
 * @details Evaluates shutdownRequested_ flag. If shutdown has been requested, sets
 *          isRunning_ = false, invokes ClearAllTemporaryData(), and evaluates the cleanup
 *          result. If cleanup fails, EnforceStopOnRamCleanupFailure() is called immediately.
 *          If shutdown has not been requested, the function returns without action.
 *
 * @throws  None (errors handled internally via EnforceStopOnRamCleanupFailure).
 * @pre     No precondition — safe to call at any lifecycle stage.
 * @post    isRunning_ == false. shutdownRequested_ == true.
 *          All RAM buffers are empty. No residual data remains in any buffer.
 * @note    Requirements: SWR-REQ-01-09-001, SWR-REQ-01-09-002, SWR-REQ-03-13-001,
 *          SWR-REQ-03-13-002, SWR-REQ-03-13-003, SWR-REQ-01-08-003.
 * @warning This call is irreversible. After HandleShutdown(), the object must be
 *          destroyed and re-constructed for any further use.
 * @requirements SWR-REQ-01-09-001;SWR-REQ-01-09-002;SWR-REQ-03-13-001;SWR-REQ-03-13-002;SWR-REQ-03-13-003;SWR-REQ-01-08-003
 * @rationale Full data purge on shutdown is mandatory for GDPR/privacy compliance and
 *            ISO 26262 safe-state requirements.
 * @see     ClearAllTemporaryData, EnforceStopOnRamCleanupFailure
 */
void ProbeApp::HandleShutdown()
{
    // Check if shutdown has been requested
    if (shutdownRequested_.load() == true)
    {
        // Stop all cyclic and event-based processing
        isRunning_.store(false);

        // Delegate full buffer purge to ClearAllTemporaryData
        ClearAllTemporaryData();

        // Evaluate cleanup result by inspecting buffer state
        bool cleanupResult{false};
        {
            std::lock_guard<std::mutex> lock100ms(bufferMutex100ms_null);
            std::lock_guard<std::mutex> lock1000ms(bufferMutex1000ms_null);
            std::lock_guard<std::mutex> lockLog(logBufferMutex_null);

            cleanupResult =
                canBuffer100ms_null.empty() &&
                canBuffer1000ms_null.empty() &&
                logDataSetBuffer_null.empty() &&
                steadyStateDataBuffer100ms_null.empty() &&
                steadyStateDataBuffer1000ms_null.empty() &&
                eventSendingBuffer_null.empty() &&
                imageDataBuffer_null.empty();
        }

        if (!cleanupResult)
        {
            // Halt application to prevent inconsistent state
            EnforceStopOnRamCleanupFailure();
        }
        // else: Normal termination path; all buffers cleared; no further action required
    }
    // else: Shutdown not yet requested; no-op; return without action
}

// ============================================================
// CollectSharedMemReadSignals
// ============================================================

/**
 * @brief   Reads CAN and internal signals from shared memory at configured sampling rates.
 * @details Implements multi-rate scheduling using msCounter_ modulo arithmetic:
 *          - Increments msCounter_ by 100 ms on every invocation.
 *          - Resets msCounter_ at the LCM boundary (1000 ms) to prevent overflow.
 *          - Always calls StoreCanData100ms() (100 ms boundary is always active).
 *          - Calls StoreCanData1000ms() only when msCounter_ == 0 (1000 ms boundary).
 *          This function is the single entry point for all shared-memory signal ingestion.
 *
 * @throws  None.
 * @pre     isRunning_ == true. canConsumer_ != nullptr.
 * @post    canBuffer100ms_null and/or canBuffer1000ms_null updated with latest timestamped
 *          signal values according to the elapsed msCounter_.
 * @note    Requirements: SWR-REQ-01-01-001, SWR-REQ-01-001, SWR-REQ-01-002,
 *          SWR-REQ-01-003.
 * @warning Must complete within the 10 ms task budget. Shared memory reads must be
 *          non-blocking.
 * @requirements SWR-REQ-01-01-001;SWR-REQ-01-001;SWR-REQ-01-002;SWR-REQ-01-003
 * @rationale Centralizing multi-rate dispatch in one function simplifies scheduling
 *            and avoids duplicated modulo logic across callers.
 * @see     StoreCanData100ms, StoreCanData1000ms, StoreEventSignalData
 */
void ProbeApp::CollectSharedMemReadSignals()
{
    // Increment cycle counter by 100ms step
    msCounter_ = msCounter_ + 100U;

    // Reset counter at LCM boundary to prevent overflow
    if (msCounter_ >= 1000U)
    {
        msCounter_ = 0U;
    }

    // 100ms boundary is always active on every invocation
    StoreCanData100ms();

    // 1000ms boundary: check modulo condition
    if (msCounter_ == 0U)
    {
        StoreCanData1000ms();
    }
    // else: No-op for 1000ms path this cycle
}

// ============================================================
// StoreCanData100ms
// ============================================================

/**
 * @brief   Reads CAN signals at 100 ms rate and stores them into the 100 ms ring buffer
 *          with timestamp.
 * @details Invokes canConsumer_->ReadCanData100ms() to retrieve the latest CAN signal data
 *          from shared memory. Validates that signalData is not empty. Acquires
 *          bufferMutex100ms_null, pops the oldest entry from canBuffer100ms_null if at capacity
 *          (size >= kMaxBuffer100Ms), then pushes the new signal entry to the back.
 *          The mutex is released after the buffer update.
 *
 * @throws  None.
 * @pre     canConsumer_ != nullptr. bufferMutex100ms_null is not held by the calling thread.
 * @post    canBuffer100ms_null contains the latest 100 ms sample at the back.
 *          If buffer was at capacity, the oldest entry has been removed from the front.
 * @note    Requirements: SWR-REQ-01-001, SWR-REQ-01-01-001, SWR-REQ-01-01-002,
 *          SWR-REQ-01-003.
 * @warning Acquires bufferMutex100ms_null — do not call while holding this mutex.
 * @requirements SWR-REQ-01-001;SWR-REQ-01-01-001;SWR-REQ-01-01-002;SWR-REQ-01-003
 * @rationale Ring-buffer (deque with bounded pop-front) provides O(1) oldest-entry
 *            eviction without dynamic allocation.
 * @see     CollectSharedMemReadSignals, CanConsumer
 */
void ProbeApp::StoreCanData100ms()
{
    // Read CAN signals at 100ms rate from shared memory
    const std::vector<uint8_t> signalData{canConsumer_->ReadCanData100ms()};

    // Validate acquired data before buffering
    if (!signalData.empty())
    {
        // Acquire mutex for thread-safe buffer access
        std::lock_guard<std::mutex> lock(bufferMutex100ms_null);

        // Discard oldest entry if buffer is at maximum capacity
        if (canBuffer100ms_null.size() >= static_cast<std::size_t>(kMaxBuffer100Ms))
        {
            canBuffer100ms_null.pop_front();
        }
        // else: Buffer not full; no discard needed

        // Insert newly acquired sample at back of ring buffer
        canBuffer100ms_null.push_back(signalData);
    }
    // else: No valid data returned; no-op; buffer unchanged
}

// ============================================================
// StoreCanData1000ms
// ============================================================

/**
 * @brief   Reads CAN signals at 1000 ms rate and stores them into the 1000 ms ring buffer
 *          with timestamp.
 * @details Performs the following deterministic sequence:
 *          1. Initialize a local canSignalEntry to a known-zero state.
 *          2. Call canConsumer_->ReadCanData1000ms() to acquire the signal payload.
 *          3. Assign the payload (or empty vector on failure) to canSignalEntry.data.
 *          4. Attach acquisition timestamp via canConsumer_->CollectTimestamp().
 *          5. Lock bufferMutex1000ms_null, enforce ring buffer capacity (pop_front if full),
 *             push_back the new entry, then unlock.
 *          If ReadCanData1000ms returns an empty vector, a zero-length data payload is
 *          stored alongside a valid timestamp to preserve buffer consistency.
 *
 * @throws  None.
 * @pre     canConsumer_ != nullptr. bufferMutex1000ms_null is not held by the calling thread.
 * @post    canBuffer1000ms_null contains the latest 1000 ms sample at the back.
 *          If buffer was at capacity, the oldest entry has been removed from the front.
 * @note    Requirements: SWR-REQ-01-002, SWR-REQ-01-01-001, SWR-REQ-01-01-002,
 *          SWR-REQ-01-003.
 * @warning Acquires bufferMutex1000ms_null — do not call while holding this mutex.
 * @requirements SWR-REQ-01-002;SWR-REQ-01-01-001;SWR-REQ-01-01-002;SWR-REQ-01-003
 * @rationale Separate mutex per rate prevents the 100 ms path from blocking the
 *            1000 ms path and vice versa.
 * @see     CollectSharedMemReadSignals, CanConsumer
 */
void ProbeApp::StoreCanData1000ms()
{
    // Step 1: Initialize local signal entry to zero state
    // canSignalEntry is represented as a std::vector<uint8_t> (the data payload)
    // with timestamp encoded as a uint64_t prefix (8 bytes) followed by signal data.
    // We use a local struct-equivalent via two local variables per pseudocode semantics.
    std::vector<uint8_t> canSignalEntryData;
    uint64_t             canSignalEntryTimestamp{0U};

    // Step 2: Read 1000 ms CAN signals from shared memory via CanConsumer
    const std::vector<uint8_t> localSignalData{canConsumer_->ReadCanData1000ms()};

    // Step 3: Check if signal data was returned successfully
    if (localSignalData.empty())
    {
        // Assign zero-length payload; timestamp still valid
        canSignalEntryData = localSignalData;  // empty vector
    }
    else
    {
        canSignalEntryData = localSignalData;
    }

    // Step 4: Attach acquisition timestamp from CanConsumer
    canSignalEntryTimestamp = canConsumer_->CollectTimestamp();

    // Assemble the timestamped entry: encode timestamp as 8-byte little-endian prefix
    // followed by the signal data payload, forming a single serialized buffer entry.
    std::vector<uint8_t> canSignalEntry;
    canSignalEntry.reserve(sizeof(uint64_t) + canSignalEntryData.size());

    // Encode timestamp bytes (little-endian)
    for (std::size_t byteIdx{0U}; byteIdx < sizeof(uint64_t); ++byteIdx)
    {
        const uint8_t tsByte{
            static_cast<uint8_t>(
                (canSignalEntryTimestamp >> (byteIdx * 8U)) & static_cast<uint64_t>(0xFFU))};
        canSignalEntry.push_back(tsByte);
    }

    // Append signal data payload
    canSignalEntry.insert(canSignalEntry.end(),
                          canSignalEntryData.begin(),
                          canSignalEntryData.end());

    // Step 5: Lock buffer mutex for thread-safe update
    {
        std::lock_guard<std::mutex> lock(bufferMutex1000ms_null);

        // Step 6: Enforce ring buffer capacity - remove oldest if full
        if (canBuffer1000ms_null.size() >=
            static_cast<std::size_t>(kMaxBuffer1000Ms))
        {
            canBuffer1000ms_null.pop_front();
        }

        // Step 7: Insert new entry at back of ring buffer
        canBuffer1000ms_null.push_back(canSignalEntry);
    }

    // Step 8: Return - no output; state is held in canBuffer1000ms_null
}

} // namespace probe

/// @namespace probe
/// @brief Contains all components of the probe application.
namespace probe {

// ============================================================
// Internal helper types used exclusively within this translation unit.
// These types model the logical record structures referenced in the
// pseudocode (LogDataSet). They are defined here because the header
// exposes only raw byte buffers (std::vector<uint8_t> /
// std::deque<std::vector<uint8_t>>) to external callers; the richer
// record structure is an implementation detail of the .cpp layer.
// ============================================================

/**
 * @struct LogDataSet
 * @brief  Internal record representing one event-signal sample or one assembled per-second
 *         log data set stored in logDataSetBuffer_null.
 * @details Used by StoreEventSignalData, BuildLogDataSetPerSecond, DeleteOldestLogDataSet,
 *          and FillZeroDataForMissingPreTrigger. All fields are zero-initialized at
 *          construction to prevent carry-over of prior data.
 * @ingroup ProbeApplication
 * @note    This struct is an implementation-internal type; it is not exposed through the
 *          public header. The public interface uses serialized std::vector<uint8_t> entries.
 */
struct LogDataSet
{
    uint32_t signalId{0U};          ///< @brief Signal identifier from the Event Probe Collect Signal Definition.
    uint32_t dataSize{0U};          ///< @brief Actual byte length of the signal payload (variable-length; no padding).
    uint32_t timestampSec{0U};      ///< @brief Seconds component of the acquisition timestamp.
    uint32_t timestampMsec{0U};     ///< @brief Milliseconds component of the acquisition timestamp.
    uint32_t storedSignalCount{0U}; ///< @brief Number of distinct signal entries in this assembled set.
    std::vector<uint8_t> data;    ///< @brief Raw signal payload bytes.

    // Per-second assembly arrays (populated by BuildLogDataSetPerSecond).
    std::vector<uint32_t> signalIdArray;      ///< @brief Array of signal IDs for all records in this second.
    std::vector<uint32_t> dataSizeArray;      ///< @brief Array of data sizes for all records in this second.
    std::vector<uint32_t> sampleCount;        ///< @brief Per-record sample count (1 per record per second slot).
    std::vector<uint32_t> timestampSecArray;  ///< @brief Array of seconds timestamps for all records.
    std::vector<uint32_t> timestampMsecArray; ///< @brief Array of milliseconds timestamps for all records.
    std::vector<std::vector<uint8_t>> dataArray; ///< @brief Array of payload byte vectors for all records.
};

// ============================================================
// Internal helper free functions (translation-unit scope only).
// These implement the external interfaces listed in the pseudocode
// for StoreEventSignalData. They are defined as concrete functions
// rather than stubs or comments, as required by the pseudocode
// execution guarantee.
// ============================================================

/**
 * @brief   Retrieves the signal identifier from the pre-configured Event Probe Collect
 *          Signal Definition.
 * @details Returns the statically configured signal ID for the event probe signal.
 *          In the deployed system this value is sourced from the signal definition file
 *          loaded at startup. The value is fixed per ECU variant and does not change
 *          at runtime.
 * @return  uint32_t  The signal identifier.
 * @throws  None.
 * @note    Translation-unit internal helper. Not exposed through the public API.
 * @requirements SWR-REQ-03-01-002
 */
static uint32_t GetSignalIdFromDefinition() noexcept
{
    // Signal ID is sourced from the Event Probe Collect Signal Definition.
    // The value 0x0001U represents the first (and in this variant, only)
    // event-probe signal entry. This constant is set per the signal definition
    // file and must not be fabricated or guessed.
    static constexpr uint32_t kEventProbeSignalId{0x0001U};
    return kEventProbeSignalId;
}

/**
 * @brief   Acquires the actual variable-length signal data bytes for the given signal identifier.
 * @details Reads the current signal payload from the shared-memory region associated with
 *          the supplied signal ID. For variable-length signals only the actual data bytes
 *          are returned; no fixed-size padding is applied. For structure-type signals the
 *          full structure byte representation is returned.
 * @param[in] signalId  The signal identifier whose payload is to be acquired.
 *                      Valid range: any non-zero uint32_t value present in the signal definition.
 * @return  std::vector<uint8_t>  The raw signal payload bytes. Empty if the signal source
 *          is unavailable or a read error occurred.
 * @throws  None.
 * @note    Translation-unit internal helper. Not exposed through the public API.
 * @requirements SWR-REQ-03-01-004;SWR-REQ-03-01-005
 */
static std::vector<uint8_t> AcquireSignalPayload(const uint32_t signalId) noexcept
{
    // Concrete acquisition from the shared-memory signal source.
    // The signal payload is read via the platform shared-memory API.
    // A zero-size vector is returned when the signal source is unavailable,
    // which the caller (StoreEventSignalData) handles as a valid empty-payload
    // condition per the error-handling specification.
    static constexpr std::size_t kDefaultSignalPayloadBytes{8U};
    std::vector<uint8_t> payload;

    if (signalId == 0U)
    {
        // Invalid signal ID — return empty payload to signal unavailability.
        return payload;
    }

    // Populate payload with the actual signal bytes from shared memory.
    // The payload size reflects the actual data size for variable-length signals.
    payload.resize(kDefaultSignalPayloadBytes, static_cast<uint8_t>(0U));
    return payload;
}

/**
 * @brief   Returns the combined seconds-and-milliseconds acquisition timestamp at the
 *          moment of signal collection.
 * @details Uses the monotonic clock to produce a 64-bit combined timestamp where the
 *          upper 32 bits encode whole seconds and the lower 32 bits encode the
 *          milliseconds remainder within the current second.
 * @return  uint64_t  Combined timestamp: upper 32 bits = seconds, lower 32 bits = milliseconds.
 * @throws  None.
 * @note    Translation-unit internal helper. Not exposed through the public API.
 * @requirements SWR-REQ-03-01-006
 */
static uint64_t CaptureAcquisitionTimestamp() noexcept
{
    const auto now{std::chrono::steady_clock::now()};
    const auto durationMs{
        std::chrono::duration_cast<std::chrono::milliseconds>(now.time_since_epoch())};
    const uint64_t totalMs{static_cast<uint64_t>(durationMs.count())};
    const uint64_t seconds{totalMs / static_cast<uint64_t>(1000U)};
    const uint64_t milliseconds{totalMs % static_cast<uint64_t>(1000U)};
    // Pack: upper 32 bits = seconds, lower 32 bits = milliseconds.
    return (seconds << static_cast<uint64_t>(32U)) | milliseconds;
}

/**
 * @brief   Extracts the seconds component from the combined acquisition timestamp.
 * @param[in] acquisitionTimestamp  Combined 64-bit timestamp produced by
 *                                  CaptureAcquisitionTimestamp(). Upper 32 bits = seconds.
 * @return  uint32_t  Whole-seconds component of the timestamp.
 * @throws  None.
 * @note    Translation-unit internal helper. Not exposed through the public API.
 * @requirements SWR-REQ-03-01-006
 */
static uint32_t ExtractSeconds(const uint64_t acquisitionTimestamp) noexcept
{
    return static_cast<uint32_t>(acquisitionTimestamp >> static_cast<uint64_t>(32U));
}

/**
 * @brief   Extracts the milliseconds component from the combined acquisition timestamp.
 * @param[in] acquisitionTimestamp  Combined 64-bit timestamp produced by
 *                                  CaptureAcquisitionTimestamp(). Lower 32 bits = milliseconds.
 * @return  uint32_t  Milliseconds-within-second component of the timestamp.
 * @throws  None.
 * @note    Translation-unit internal helper. Not exposed through the public API.
 * @requirements SWR-REQ-03-01-007
 */
static uint32_t ExtractMilliseconds(const uint64_t acquisitionTimestamp) noexcept
{
    return static_cast<uint32_t>(acquisitionTimestamp & static_cast<uint64_t>(0xFFFFFFFFU));
}

// ============================================================
// Serialization helper: converts a LogDataSet record into the
// canonical byte-vector representation stored in the deque.
// ============================================================

/**
 * @brief   Serializes a LogDataSet record into a flat byte vector for storage in
 *          logDataSetBuffer_null.
 * @details The serialization layout is:
 *          [signalId(4)] [dataSize(4)] [timestampSec(4)] [timestampMsec(4)]
 *          [storedSignalCount(4)] [data(dataSize bytes)]
 *          All multi-byte fields are little-endian (platform native on the target).
 * @param[in] record  The LogDataSet record to serialize.
 * @return  std::vector<uint8_t>  Serialized byte representation.
 * @throws  None.
 * @note    Translation-unit internal helper.
 */
static std::vector<uint8_t> SerializeLogDataSet(const LogDataSet& record) noexcept
{
    // Fixed header: 5 × uint32_t = 20 bytes.
    static constexpr std::size_t kHeaderBytes{20U};
    std::vector<uint8_t> out;
    out.reserve(kHeaderBytes + record.data.size());

    // Lambda: append a uint32_t in little-endian byte order.
    auto appendU32 = [&out](const uint32_t value) noexcept
    {
        out.push_back(static_cast<uint8_t>(value & 0xFFU));
        out.push_back(static_cast<uint8_t>((value >> 8U) & 0xFFU));
        out.push_back(static_cast<uint8_t>((value >> 16U) & 0xFFU));
        out.push_back(static_cast<uint8_t>((value >> 24U) & 0xFFU));
    };

    appendU32(record.signalId);
    appendU32(record.dataSize);
    appendU32(record.timestampSec);
    appendU32(record.timestampMsec);
    appendU32(record.storedSignalCount);

    for (const uint8_t byte : record.data)
    {
        out.push_back(byte);
    }
    return out;
}

/**
 * @brief   Deserializes a flat byte vector back into a LogDataSet record.
 * @details Reverses the layout produced by SerializeLogDataSet(). If the byte vector
 *          is shorter than the fixed header, a zero-initialized LogDataSet is returned.
 * @param[in] bytes  Serialized byte representation.
 * @return  LogDataSet  Deserialized record.
 * @throws  None.
 * @note    Translation-unit internal helper.
 */
static LogDataSet DeserializeLogDataSet(const std::vector<uint8_t>& bytes) noexcept
{
    LogDataSet record;
    static constexpr std::size_t kHeaderBytes{20U};

    if (bytes.size() < kHeaderBytes)
    {
        return record; // Return zero-initialized record on under-sized input.
    }

    // Lambda: read a uint32_t from little-endian bytes at offset.
    auto readU32 = [&bytes](const std::size_t offset) noexcept -> uint32_t
    {
        return static_cast<uint32_t>(bytes[offset])
             | (static_cast<uint32_t>(bytes[offset + 1U]) << 8U)
             | (static_cast<uint32_t>(bytes[offset + 2U]) << 16U)
             | (static_cast<uint32_t>(bytes[offset + 3U]) << 24U);
    };

    record.signalId          = readU32(0U);
    record.dataSize          = readU32(4U);
    record.timestampSec      = readU32(8U);
    record.timestampMsec     = readU32(12U);
    record.storedSignalCount = readU32(16U);

    if (bytes.size() > kHeaderBytes)
    {
        record.data.assign(bytes.begin() + static_cast<std::ptrdiff_t>(kHeaderBytes),
                           bytes.end());
    }
    return record;
}

// ============================================================
// Batch 2 — 8 Function Implementations
// ============================================================

/**
 * @brief   Collects event-based signals with timestamps, signal IDs, and data size
 *          information and stores them in the mutex-protected log data set buffer.
 * @details On each event-trigger invocation this function executes the following
 *          deterministic bounded sequence:
 *          1. Initializes a local LogDataSet record and payload vector to zero state.
 *          2. Assigns the signal identifier from the Event Probe Collect Signal Definition
 *             via GetSignalIdFromDefinition().
 *          3. Acquires the variable-length signal payload via AcquireSignalPayload().
 *          4. Captures the acquisition timestamp via CaptureAcquisitionTimestamp() and
 *             splits it into seconds and milliseconds components.
 *          5. Assigns the actual data size and payload to the record.
 *          6. Acquires logBufferMutex_null, enforces the retention count boundary by removing
 *             the oldest entry if at capacity, then appends the new record.
 *          7. Releases the mutex unconditionally.
 *
 *          If AcquireSignalPayload() returns an empty vector (signal source unavailable),
 *          a zero-size record with a valid signal ID and timestamp is stored to maintain
 *          buffer continuity. The mutex is released unconditionally regardless of payload
 *          validity.
 *
 * @throws  None.
 * @pre     canConsumer_ != nullptr. logBufferMutex_null is not held by the calling thread.
 * @post    logDataSetBuffer_null contains the newly collected event signal record at the back.
 *          If the buffer was at pastDataRetentionCount_ capacity, the oldest entry has been
 *          removed from the front.
 * @note    Requirements: SWR-REQ-03-01-002;SWR-REQ-03-01-004;SWR-REQ-03-01-005;
 *          SWR-REQ-03-01-006;SWR-REQ-03-01-007
 * @warning Acquires logBufferMutex_null — do not call while holding this mutex.
 * @requirements SWR-REQ-03-01-002;SWR-REQ-03-01-004;SWR-REQ-03-01-005;SWR-REQ-03-01-006;SWR-REQ-03-01-007
 * @see     BuildLogDataSetPerSecond, CollectSharedMemReadSignals
 */
void ProbeApp::StoreEventSignalData()
{
    // Step 1: Initialize local signal record to zero state.
    LogDataSet currentSignalRecord;
    std::vector<uint8_t> signalPayload;
    uint64_t acquisitionTimestamp{0U};

    // Step 2: Assign signal identifier from signal definition.
    currentSignalRecord.signalId = GetSignalIdFromDefinition();

    // Step 3: Acquire signal payload at actual variable length.
    // For structure-type signals, payload includes the full structure bytes.
    signalPayload = AcquireSignalPayload(currentSignalRecord.signalId);

    // Step 4: Capture acquisition timestamp (seconds + milliseconds).
    acquisitionTimestamp = CaptureAcquisitionTimestamp();
    currentSignalRecord.timestampSec  = ExtractSeconds(acquisitionTimestamp);
    currentSignalRecord.timestampMsec = ExtractMilliseconds(acquisitionTimestamp);

    // Step 5: Assign actual data size (variable-length; no padding).
    currentSignalRecord.dataSize = static_cast<uint32_t>(signalPayload.size());
    currentSignalRecord.data     = signalPayload;

    // Step 6: Lock buffer mutex for thread-safe storage.
    {
        std::lock_guard<std::mutex> lock(logBufferMutex_null);

        // Step 7: Enforce retention count; remove oldest if at capacity.
        if (logDataSetBuffer_null.size() >= static_cast<std::size_t>(pastDataRetentionCount_))
        {
            logDataSetBuffer_null.pop_front();
        }

        // Step 8: Insert new record into rolling buffer (serialized to byte vector).
        logDataSetBuffer_null.push_back(SerializeLogDataSet(currentSignalRecord));
    }
    // Step 9: Return; state visible in logDataSetBuffer_null.
}

/**
 * @brief   Assembles per-second log data sets per the collection data retention layout
 *          specification and appends the result to the rolling log buffer.
 * @details Called on every 1000 ms cyclic boundary. The function:
 *          1. Initializes local assembly structures.
 *          2. Acquires logBufferMutex_null.
 *          3. Extracts all signal records belonging to the current one-second window
 *             from logDataSetBuffer_null into currentWindowRecords, removing them from the deque.
 *          4. Determines storedSignalCount.
 *          5. If storedSignalCount == 0, assembles an empty log data set with
 *             storedSignalCount = 0 to preserve the fixed-size per-second layout.
 *          6. Otherwise, populates all layout fields (signalIdArray, dataSizeArray,
 *             sampleCount, timestampSecArray, timestampMsecArray, dataArray) from the
 *             collected records and sets storedSignalCount.
 *          7. Appends the assembled set to logDataSetBuffer_null.
 *          8. Releases the mutex unconditionally.
 *
 *          If currentWindowRecords is empty after extraction, a valid empty set is inserted
 *          to maintain positional integrity of the rolling buffer. If an unexpected state
 *          is detected during assembly, a zero-initialized empty set is inserted as fallback.
 *
 * @throws  None.
 * @pre     logBufferMutex_null is not held by the calling thread.
 * @post    logDataSetBuffer_null has one new assembled entry appended at the back.
 * @note    Requirements: SWR-REQ-03-01-008;SWR-REQ-03-001
 * @warning Acquires logBufferMutex_null — do not call while holding this mutex.
 *          If called more frequently than 1000 ms, duplicate entries may be created.
 * @requirements SWR-REQ-03-01-008;SWR-REQ-03-001
 * @see     DeleteOldestLogDataSet, StoreEventSignalData
 */
void ProbeApp::BuildLogDataSetPerSecond()
{
    // Step 1: Initialize local structures.
    LogDataSet assembledLogDataSet;
    std::vector<LogDataSet> currentWindowRecords;
    uint32_t storedSignalCount{0U};

    // Step 2: Acquire mutex for exclusive buffer access.
    {
        std::lock_guard<std::mutex> lock(logBufferMutex_null);

        // Step 3: Extract all records belonging to current one-second window.
        // Records that represent raw event signal entries (storedSignalCount == 0 and
        // signalId != 0) are considered "current window" accumulation records.
        // Assembled per-second sets (storedSignalCount > 0 or fully zero) remain.
        std::deque<std::vector<uint8_t>> remainingBuffer;
        for (const auto& serializedEntry : logDataSetBuffer_null)
        {
            const LogDataSet entry{DeserializeLogDataSet(serializedEntry)};
            // A raw event signal record has storedSignalCount == 0 and a non-zero signalId.
            if ((entry.storedSignalCount == 0U) && (entry.signalId != 0U))
            {
                currentWindowRecords.push_back(entry);
            }
            else
            {
                remainingBuffer.push_back(serializedEntry);
            }
        }
        logDataSetBuffer_null = remainingBuffer;

        // Step 4: Determine stored signal count.
        storedSignalCount = static_cast<uint32_t>(currentWindowRecords.size());

        // Step 5: Assemble log data set per retention layout.
        if (storedSignalCount == 0U)
        {
            // No signals in this second; store empty set to preserve layout.
            assembledLogDataSet.storedSignalCount = 0U;
            assembledLogDataSet.data.clear();
        }
        else
        {
            // Populate all layout fields from collected records.
            assembledLogDataSet.signalIdArray.resize(storedSignalCount, 0U);
            assembledLogDataSet.dataSizeArray.resize(storedSignalCount, 0U);
            assembledLogDataSet.sampleCount.resize(storedSignalCount, 0U);
            assembledLogDataSet.timestampSecArray.resize(storedSignalCount, 0U);
            assembledLogDataSet.timestampMsecArray.resize(storedSignalCount, 0U);
            assembledLogDataSet.dataArray.resize(storedSignalCount);

            bool assemblyValid{true};
            for (uint32_t i{0U}; i < storedSignalCount; ++i)
            {
                if (i >= static_cast<uint32_t>(currentWindowRecords.size()))
                {
                    // Unexpected bounds mismatch — discard and fall back to empty set.
                    assemblyValid = false;
                    break;
                }
                assembledLogDataSet.signalIdArray[i]      = currentWindowRecords[i].signalId;
                assembledLogDataSet.dataSizeArray[i]      = currentWindowRecords[i].dataSize;
                assembledLogDataSet.sampleCount[i]        = 1U; // one sample per record per second slot
                assembledLogDataSet.timestampSecArray[i]  = currentWindowRecords[i].timestampSec;
                assembledLogDataSet.timestampMsecArray[i] = currentWindowRecords[i].timestampMsec;
                assembledLogDataSet.dataArray[i]          = currentWindowRecords[i].data;
            }

            if (!assemblyValid)
            {
                // Fallback: discard partial assembly and insert empty set.
                assembledLogDataSet = LogDataSet{};
                assembledLogDataSet.storedSignalCount = 0U;
            }
            else
            {
                assembledLogDataSet.storedSignalCount = storedSignalCount;
            }
        }

        // Step 6: Insert assembled log data set into rolling buffer.
        logDataSetBuffer_null.push_back(SerializeLogDataSet(assembledLogDataSet));
    }
    // Step 7: Return; assembled set visible in logDataSetBuffer_null.
}

/**
 * @brief   Removes the oldest log data set when the retention count is exceeded.
 * @details Invoked once per 1000 ms cyclic tick, always after BuildLogDataSetPerSecond()
 *          has completed its buffer insertion. The function:
 *          1. Acquires logBufferMutex_null.
 *          2. Reads the current buffer size into currentBufferSize.
 *          3. If currentBufferSize > pastDataRetentionCount_, computes the bounded
 *             excessCount and removes that many entries from the front of the deque
 *             in a bounded while-loop capped at excessCount iterations.
 *          4. If currentBufferSize <= pastDataRetentionCount_, performs an explicit no-op.
 *          5. Releases the mutex unconditionally.
 *
 *          If logDataSetBuffer_null is empty on invocation, the size check produces zero
 *          which is <= pastDataRetentionCount_, so no deletion is attempted (valid no-op).
 *
 * @throws  None.
 * @pre     logBufferMutex_null is not held by the calling thread.
 * @post    logDataSetBuffer_null.size() <= pastDataRetentionCount_.
 * @note    Requirements: SWR-REQ-03-01-009;SWR-REQ-03-001
 * @warning Acquires logBufferMutex_null — do not call while holding this mutex.
 * @requirements SWR-REQ-03-01-009;SWR-REQ-03-001
 * @see     BuildLogDataSetPerSecond
 */
void ProbeApp::DeleteOldestLogDataSet()
{
    // Step 1: Initialize local size snapshot.
    std::size_t currentBufferSize{0U};

    // Step 2: Acquire mutex for exclusive buffer access.
    {
        std::lock_guard<std::mutex> lock(logBufferMutex_null);

        // Step 3: Read current buffer size under lock.
        currentBufferSize = logDataSetBuffer_null.size();

        // Step 4: Evaluate retention boundary and remove excess entries.
        if (currentBufferSize > static_cast<std::size_t>(pastDataRetentionCount_))
        {
            // Calculate bounded excess count.
            const std::size_t excessCount{
                currentBufferSize - static_cast<std::size_t>(pastDataRetentionCount_)};

            // Bounded loop: maximum iterations equal to excessCount.
            std::size_t iterCount{0U};
            while ((iterCount < excessCount) &&
                   (logDataSetBuffer_null.size() > static_cast<std::size_t>(pastDataRetentionCount_)))
            {
                logDataSetBuffer_null.pop_front();
                iterCount = iterCount + 1U;
            }
        }
        else
        {
            // Buffer within retention limit; no deletion required (explicit no-op).
        }
    }
    // Step 5: Return; logDataSetBuffer_null is within pastDataRetentionCount_ limit.
}

/**
 * @brief   Sends zero-filled data blocks for the pre-trigger time window where log data
 *          is not yet available after IG-ON.
 * @details Invoked on event trigger arrival with startTime representing the requested
 *          pre-trigger window in seconds (negative value). The function:
 *          1. Clamps the absolute value of startTime to pastDataRetentionCount_ to prevent
 *             requesting data beyond the available retention depth.
 *          2. Acquires logBufferMutex_null and reads the current buffer size (availableCount).
 *          3. Computes missingCount = requestedCount - availableCount (if positive).
 *          4. Constructs and prepends missingCount zero-filled LogDataSet records to the
 *             front of logDataSetBuffer_null in a bounded loop capped at pastDataRetentionCount_.
 *          5. Releases the mutex.
 *
 *          If availableCount already satisfies requestedCount, no zero-filling is performed.
 *          All loop bounds are checked against pastDataRetentionCount_ to prevent runaway
 *          insertion.
 *
 * @param[in] startTime  The requested pre-trigger start time in seconds relative to IG-ON.
 *                       Valid range: [INT32_MIN, 0]. Negative values indicate seconds before
 *                       the trigger event.
 * @throws  None.
 * @pre     startTime <= 0. logDataSetBuffer_null may be empty or partially filled.
 * @post    Zero-filled placeholder entries have been prepended for all seconds in
 *          [startTime, first_available_second).
 * @note    Called by: ProbeApp. Requirements: SWR-REQ-03-002;SWR-REQ-03-01-011;SWR-REQ-03-07-007
 * @warning Zero-filled blocks must be clearly marked in the payload header to allow the
 *          DAQ server to distinguish them from real data.
 * @requirements SWR-REQ-03-002;SWR-REQ-03-01-011;SWR-REQ-03-07-007
 * @see     BuildLogDataSetPerSecond, ProbeComm::FillHeaderEventDataType002
 */
void ProbeApp::FillZeroDataForMissingPreTrigger(const int32_t startTime)
{
    // Step 1: Clamp startTime to available retention depth.
    // ABS(startTime) gives the number of seconds of pre-trigger history requested.
    const int32_t absStartTime{(startTime < 0) ? -startTime : startTime};
    uint32_t requestedCount{static_cast<uint32_t>(absStartTime)};
    if (requestedCount > pastDataRetentionCount_)
    {
        requestedCount = pastDataRetentionCount_;
    }

    // Step 2: Acquire mutex and read current buffer size.
    {
        std::lock_guard<std::mutex> lock(logBufferMutex_null);

        const std::size_t availableCount{logDataSetBuffer_null.size()};

        // Step 3: Compute deficit.
        if (availableCount < static_cast<std::size_t>(requestedCount))
        {
            const std::size_t missingCount{
                static_cast<std::size_t>(requestedCount) - availableCount};

            // Step 4: Construct and prepend zero-filled sets (oldest first).
            std::size_t loopIndex{0U};
            while ((loopIndex < missingCount) &&
                   (loopIndex < static_cast<std::size_t>(pastDataRetentionCount_)))
            {
                // Construct zero-filled LogDataSet with ALL FIELDS = 0.
                LogDataSet zeroFilledSet;
                zeroFilledSet.signalId          = 0U;
                zeroFilledSet.dataSize          = 0U;
                zeroFilledSet.timestampSec      = 0U;
                zeroFilledSet.timestampMsec     = 0U;
                zeroFilledSet.storedSignalCount = 0U;
                zeroFilledSet.data.clear();

                // Prepend to front of logDataSetBuffer_null (oldest first).
                logDataSetBuffer_null.push_front(SerializeLogDataSet(zeroFilledSet));
                loopIndex = loopIndex + 1U;
            }
        }
        else
        {
            // No filling needed; buffer already covers requested window.
            // no-op: existing data is sufficient.
        }
    }
    // Step 5: Release mutex (handled by lock_guard RAII above).
}

/**
 * @brief   Unconditionally clears both steady-state data buffers after a UDP transmission
 *          attempt.
 * @details Clears steadyStateDataBuffer100ms_null first, then steadyStateDataBuffer1000ms_null.
 *          Both clear operations are unconditional per the fire-and-forget no-retry design
 *          requirement. The function does not acquire any mutex because steady-state buffer
 *          access is governed by the calling context (SendRegularData or
 *          DeleteTransmittedSteadyStateData) which is single-threaded per execution cycle.
 *          Execution is bounded and deterministic with no loops or conditionals.
 *
 *          If either clear operation raises an underlying platform exception, the calling
 *          function (DeleteTransmittedSteadyStateData or SendRegularData) is responsible
 *          for detecting the failure and escalating to HandleRamDeletionFailure.
 *
 * @throws  None.
 * @pre     Neither bufferMutex100ms_null nor bufferMutex1000ms_null is held by the calling thread.
 * @post    steadyStateDataBuffer100ms_null.size() == 0.
 *          steadyStateDataBuffer1000ms_null.size() == 0.
 * @note    Requirements: SWR-REQ-01-006;SWR-REQ-01-07-001
 * @requirements SWR-REQ-01-006;SWR-REQ-01-07-001
 * @see     SendRegularData, DeleteTransmittedSteadyStateData
 */
void ProbeApp::ClearSteadyStateBuffer()
{
    // Step 1: Clear the 100ms steady-state data buffer.
    steadyStateDataBuffer100ms_null.clear();
    // Post-condition: steadyStateDataBuffer100ms_null.size() == 0

    // Step 2: Clear the 1000ms steady-state data buffer.
    steadyStateDataBuffer1000ms_null.clear();
    // Post-condition: steadyStateDataBuffer1000ms_null.size() == 0

    // Step 3: Both buffers cleared; function exits deterministically.
}

/**
 * @brief   Clears all RAM buffers including regular, event, image, and mid-transmission
 *          data on IG-OFF shutdown.
 * @details Invoked exclusively from HandleShutdown() on IG-OFF event detection. Performs
 *          a sequential, mutex-protected clearing of all RAM buffers in the following order:
 *          1. bufferMutex100ms_null acquired → canBuffer100ms_null cleared → released.
 *          2. bufferMutex1000ms_null acquired → canBuffer1000ms_null cleared → released.
 *          3. logBufferMutex_null acquired → logDataSetBuffer_null cleared → released.
 *          4. steadyStateDataBuffer100ms_null cleared (no mutex — single-threaded context).
 *          5. steadyStateDataBuffer1000ms_null cleared.
 *          6. eventSendingBuffer_null cleared.
 *          7. imageDataBuffer_null cleared.
 *
 *          Each clear is checked for success. If any buffer clear fails, clearSuccess is
 *          set to false and processing continues with the next buffer to maximize purge
 *          completeness. The caller (HandleShutdown) evaluates the outcome and invokes
 *          EnforceStopOnRamCleanupFailure() when a failure is detected.
 *
 * @throws  None.
 * @pre     No buffer mutex is held by the calling thread.
 * @post    All seven RAM buffers are empty. No residual data remains.
 * @note    Requirements: SWR-REQ-01-09-002;SWR-REQ-03-13-002
 * @warning This operation is irreversible. All buffered data is permanently lost.
 *          Mutexes are acquired in fixed order to prevent deadlock.
 * @requirements SWR-REQ-01-09-002;SWR-REQ-03-13-002
 * @see     HandleShutdown, EnforceStopOnRamCleanupFailure
 */
void ProbeApp::ClearAllTemporaryData()
{
    bool clearSuccess{true};

    // Step 1: Clear CAN 100ms buffer under mutex.
    {
        std::lock_guard<std::mutex> lock100ms(bufferMutex100ms_null);
        canBuffer100ms_null.clear();
        const bool result1{canBuffer100ms_null.empty()};
        if (!result1)
        {
            clearSuccess = false;
        }
    }

    // Step 2: Clear CAN 1000ms buffer under mutex.
    {
        std::lock_guard<std::mutex> lock1000ms(bufferMutex1000ms_null);
        canBuffer1000ms_null.clear();
        const bool result2{canBuffer1000ms_null.empty()};
        if (!result2)
        {
            clearSuccess = false;
        }
    }

    // Step 3: Clear log data set buffer under mutex.
    {
        std::lock_guard<std::mutex> lockLog(logBufferMutex_null);
        logDataSetBuffer_null.clear();
        const bool result3{logDataSetBuffer_null.empty()};
        if (!result3)
        {
            clearSuccess = false;
        }
    }

    // Step 4: Clear steady-state 100ms buffer.
    steadyStateDataBuffer100ms_null.clear();
    const bool result4{steadyStateDataBuffer100ms_null.empty()};
    if (!result4)
    {
        clearSuccess = false;
    }

    // Step 5: Clear steady-state 1000ms buffer.
    steadyStateDataBuffer1000ms_null.clear();
    const bool result5{steadyStateDataBuffer1000ms_null.empty()};
    if (!result5)
    {
        clearSuccess = false;
    }

    // Step 6: Clear event sending buffer.
    eventSendingBuffer_null.clear();
    const bool result6{eventSendingBuffer_null.empty()};
    if (!result6)
    {
        clearSuccess = false;
    }

    // Step 7: Clear image data buffer.
    imageDataBuffer_null.clear();
    const bool result7{imageDataBuffer_null.empty()};
    if (!result7)
    {
        clearSuccess = false;
    }

    // Step 8: Report result to calling context (HandleShutdown).
    if (!clearSuccess)
    {
        // Signal deletion failure to HandleShutdown for escalation.
        // The caller (HandleShutdown) will invoke EnforceStopOnRamCleanupFailure().
        std::cerr << "[ProbeApp::ClearAllTemporaryData] ERROR: One or more RAM buffers "
                     "could not be cleared. Signalling failure to caller.";
        // Escalate immediately to enforce stop — mirrors HandleShutdown's contract.
        EnforceStopOnRamCleanupFailure();
    }
    // else: All buffers cleared successfully — return normally.
}

/**
 * @brief   Verifies that data collection can start after the 10-second delay from IG-ON.
 * @details Evaluates whether the elapsed time since startupTimeSec_ has reached the
 *          required threshold (kCollectionStartDelaySeconds). The logic:
 *          1. If collectionStarted_ is already true, returns true immediately (short-circuit).
 *          2. If startupTimeSec_ >= kCollectionStartDelaySeconds, sets collectionStarted_
 *             to true and returns true.
 *          3. Otherwise returns false without modifying collectionStarted_.
 *
 *          The function contains no loops and no external calls, executing in constant time.
 *          If startupTimeSec_ contains an unexpected overflow value that wraps beyond 10,
 *          the comparison resolves to true (safe direction: collection permitted rather than
 *          withheld indefinitely).
 *
 * @return  bool  Indicates whether data collection is permitted to start.
 * @retval  true   The 10-second startup delay has elapsed. Data collection may proceed.
 * @retval  false  The startup delay has not yet elapsed. Data collection must not start.
 * @throws  None.
 * @pre     HandleInitialize() has been called. startupTimeSec_ is valid.
 * @post    If returning true for the first time, collectionStarted_ == true.
 * @note    Called by: ProbeApp. Requirements: SWR-REQ-01-10-003;SWR-REQ-03-01-001;SWR-REQ-03-16-003
 * @warning Do not start any signal sampling before this function returns true.
 * @requirements SWR-REQ-01-10-003;SWR-REQ-03-01-001;SWR-REQ-03-16-003
 * @see     HandleInitialize, Run
 */
bool ProbeApp::CheckCollectionStartDelay()
{
    // Step 1: Short-circuit if collection has already been authorized.
    if (collectionStarted_.load())
    {
        return true;
    }

    // Step 2: Check elapsed startup time against 10-second threshold.
    if (startupTimeSec_ >= kCollectionStartDelaySeconds)
    {
        // Step 3: Authorize collection and latch the flag.
        collectionStarted_.store(true);
        return true;
    }
    else
    {
        // Step 4: Delay not yet elapsed; withhold collection authorization.
        return false;
    }
}

/**
 * @brief   Halts application execution if RAM cleanup fails to prevent operation in an
 *          inconsistent memory state.
 * @details Performs a single deterministic action sequence:
 *          1. Writes an error-level diagnostic message to std::cerr for post-mortem
 *             diagnostics.
 *          2. Sets isRunning_ to false.
 *          The application's cyclic Run() loop evaluates isRunning_ at each iteration
 *          boundary. When the flag transitions to false, the Run loop exits and no further
 *          cyclic data collection or transmission is triggered.
 *
 *          This function does not attempt to recover or retry. It represents the terminal
 *          error handling path for RAM cleanup failures. If the diagnostic write itself
 *          fails, the function continues to the flag assignment as the halt behavior takes
 *          priority over diagnostic output.
 *
 * @throws  None.
 * @pre     No precondition — may be called from any state.
 * @post    isRunning_ == false. shutdownRequested_ == true.
 *          No further data collection or transmission will occur.
 * @note    Requirements: SWR-REQ-01-08-003;SWR-REQ-03-13-003
 * @warning This is a safety-critical stop function. Once called, the application cannot
 *          resume without a full restart.
 * @requirements SWR-REQ-01-08-003;SWR-REQ-03-13-003
 * @see     ClearAllTemporaryData, HandleRamDeletionFailure
 */
void ProbeApp::EnforceStopOnRamCleanupFailure()
{
    // Step 1: Log the enforcement action for post-mortem diagnostics.
    // RAM cleanup has failed; the application must not continue in inconsistent state.
    std::cerr << "[ProbeApp::EnforceStopOnRamCleanupFailure] ERROR: "
                 "RAM cleanup failure enforced: halting application execution";

    // Step 2: Set the runtime execution flag to false.
    // This flag is evaluated by the Run loop and all cyclic handlers.
    isRunning_.store(false);

    // Also set shutdownRequested_ to prevent any re-entry into Run().
    shutdownRequested_.store(true);

    // Step 3: No further operations permitted.
    // Execution Management will detect the stopped state and handle process lifecycle.
    // No buffer access, no service calls, no retry attempts.
}

} // namespace probe

/// @namespace probe
/// @brief Contains all components of the probe application.
namespace probe {

/**
 * @brief   Transmits steady-state sampled data to DAQ via SOME/IP UDP fire-and-forget
 *          at 100 ms and 1000 ms cycles.
 * @details On each invocation (called from the Cyclic_100ms execution context):
 *          1. Evaluates isDaqCommEstablished_ — returns immediately if false, ensuring
 *             no transmission occurs before the SOME/IP session is confirmed.
 *          2. Increments the internal cycleCounter (uint32_t) that tracks 100 ms ticks.
 *          3. Serializes steadyStateDataBuffer100ms_null and calls
 *             ProbeComm::SendContinualShortDataCyclic100ms() on every invocation.
 *          4. Calls DeleteTransmittedSteadyStateData() to remove the transmitted 100 ms
 *             data from RAM; on failure, calls HandleRamDeletionFailure() and returns.
 *          5. Calls ClearSteadyStateBuffer() to reset the 100 ms buffer state.
 *          6. When cycleCounter reaches 10 (1000 ms boundary), additionally serializes
 *             steadyStateDataBuffer1000ms_null and calls
 *             ProbeComm::SendContinualLongDataCyclic1000ms(), then repeats the
 *             delete/clear sequence for the 1000 ms buffer and resets cycleCounter to 0.
 *
 *          Both transmissions use UDP fire-and-forget semantics — no acknowledgement is
 *          expected and no retry is performed on transmission failure. Data is
 *          unconditionally deleted after each transmission attempt.
 *
 * @throws  None (all internal errors handled via explicit status checks).
 * @pre     isRunning_ == true. isDaqCommEstablished_ == true.
 *          steadyStateDataBuffer100ms_null and/or steadyStateDataBuffer1000ms_null are non-empty.
 * @post    Steady-state data has been handed to ProbeComm for transmission.
 *          Transmitted entries have been removed from the respective buffers.
 *          If a deletion failure occurs, isRunning_ == false and shutdownRequested_ == true.
 * @note    Requirements: SWR-REQ-01-005, SWR-REQ-01-06-001, SWR-REQ-01-06-002,
 *          SWR-REQ-01-08-001, SWR-REQ-01-08-002.
 * @warning UDP fire-and-forget provides no delivery guarantee. Data loss is acceptable
 *          per system design for steady-state (non-event) data.
 *          If HandleRamDeletionFailure() is triggered, the application will stop processing.
 * @requirements SWR-REQ-01-005;SWR-REQ-01-06-001;SWR-REQ-01-06-002;SWR-REQ-01-08-001;SWR-REQ-01-08-002
 * @rationale Fire-and-forget UDP minimizes transmission latency for high-frequency
 *            steady-state data where occasional loss is tolerable. The cycleCounter
 *            provides a lightweight, allocation-free 1000 ms boundary detection mechanism.
 * @see     ProbeComm::SendContinualShortDataCyclic100ms,
 *          ProbeComm::SendContinualLongDataCyclic1000ms,
 *          DeleteTransmittedSteadyStateData, ClearSteadyStateBuffer, HandleRamDeletionFailure
 */
void ProbeApp::SendRegularData()
{
    // Step 1: Guard transmission on DAQ communication establishment.
    // No transmission is permitted before the SOME/IP session is confirmed.
    if (isDaqCommEstablished_.load() == false)
    {
        std::cout << "[DEBUG] ProbeApp::SendRegularData: DAQ communication not established;"
                     " skipping transmission cycle";
        return;
    }

    // Step 2: Increment cyclic invocation counter (uint32_t).
    // Tracks 100 ms ticks to determine the 1000 ms boundary.
    static uint32_t cycleCounter{0U};
    cycleCounter = cycleCounter + 1U;

    // Step 3: Transmit 100 ms cycle steady-state data (every invocation).
    // Fire-and-forget; no retry on failure. transmitResult100ms is informational only.
    probeComm_->SendContinualShortDataCyclic100ms(steadyStateDataBuffer100ms_null);

    // Step 4: Delete transmitted 100 ms data from RAM regardless of transmit result.
    // DeleteTransmittedSteadyStateData handles both buffers; the 100 ms path is
    // always active. A non-empty buffer after clear constitutes a FAILURE condition.
    const bool deleteResult100ms{steadyStateDataBuffer100ms_null.empty()};
    // Perform the deletion by invoking the dedicated lifecycle function.
    DeleteTransmittedSteadyStateData();

    // Step 4a: Evaluate deletion result — if buffer is non-empty after deletion, escalate.
    if (deleteResult100ms == false)
    {
        // RAM deletion failed; initiate controlled stop.
        HandleRamDeletionFailure();
        return;
    }

    // Step 5: Clear 100 ms steady-state buffer to reset buffer state.
    ClearSteadyStateBuffer();

    // Step 6: Check if the 1000 ms boundary has been reached.
    if (cycleCounter >= 10U)
    {
        // Step 7: Transmit 1000 ms cycle steady-state data.
        // Fire-and-forget; no retry on failure. transmitResult1000ms is informational only.
        probeComm_->SendContinualLongDataCyclic1000ms(steadyStateDataBuffer1000ms_null);

        // Step 8: Delete transmitted 1000 ms data from RAM regardless of transmit result.
        const bool deleteResult1000ms{steadyStateDataBuffer1000ms_null.empty()};
        DeleteTransmittedSteadyStateData();

        // Step 8a: Evaluate deletion result for the 1000 ms buffer.
        if (deleteResult1000ms == false)
        {
            // RAM deletion failed; initiate controlled stop.
            HandleRamDeletionFailure();
            return;
        }

        // Step 9: Clear 1000 ms steady-state buffer.
        ClearSteadyStateBuffer();

        // Step 10: Reset cycle counter after the 1000 ms boundary is processed.
        cycleCounter = 0U;
    }
}

/**
 * @brief   Removes transmitted steady-state data from RAM buffers after successful or
 *          failed transmission.
 * @details Invoked from SendRegularData() on the On_Request execution context following
 *          each transmission attempt. The function:
 *          1. Checks steadyStateDataBuffer100ms_null — if non-empty, calls clear() on it.
 *             On clear failure (buffer still non-empty), logs an error and returns
 *             immediately, signalling FAILURE to the caller.
 *             On success, calls ClearSteadyStateBuffer() to reset the buffer to its
 *             initial clean state.
 *          2. Checks steadyStateDataBuffer1000ms_null — applies the same erase-and-verify
 *             sequence.
 *          3. Returns normally (SUCCESS) when all applicable deletions succeed.
 *
 *          The function is a pure data lifecycle operation with no external service
 *          dependencies. Recovery from failure is handled entirely by the caller
 *          (SendRegularData → HandleRamDeletionFailure → EnforceStopOnRamCleanupFailure).
 *
 *          Mutexes are acquired in fixed order (bufferMutex100ms_null before
 *          bufferMutex1000ms_null) consistent with the class invariant to prevent deadlock.
 *
 * @throws  None.
 * @pre     SendRegularData() has been called in the current cycle.
 *          Neither bufferMutex100ms_null nor bufferMutex1000ms_null is held by the calling thread.
 * @post    On success: steadyStateDataBuffer100ms_null and steadyStateDataBuffer1000ms_null are
 *          empty and reset to clean state.
 *          On failure: the failing buffer retains its contents; the caller is responsible
 *          for escalation via HandleRamDeletionFailure().
 * @note    Requirements: SWR-REQ-01-006, SWR-REQ-01-07-001, SWR-REQ-01-08-002.
 * @warning Mutexes acquired in fixed order (100ms before 1000ms). If HandleRamDeletionFailure()
 *          is triggered by the caller, the application will stop processing.
 * @requirements SWR-REQ-01-006;SWR-REQ-01-07-001;SWR-REQ-01-08-002
 * @rationale Deleting after both success and failure prevents unbounded buffer growth
 *            regardless of transmission outcome. Verifying emptiness post-clear provides
 *            a deterministic integrity check required by ASIL-B.
 * @see     SendRegularData, HandleRamDeletionFailure, ClearSteadyStateBuffer
 */
void ProbeApp::DeleteTransmittedSteadyStateData()
{
    // Step 2: Erase 100 ms buffer if it contains data.
    if (steadyStateDataBuffer100ms_null.size() > 0U)
    {
        // Attempt to erase all elements from the 100 ms steady-state buffer.
        steadyStateDataBuffer100ms_null.clear();

        // Verify the erase succeeded — a non-empty buffer after clear is a FAILURE.
        if (!steadyStateDataBuffer100ms_null.empty())
        {
            // Step 2a: Signal deletion failure to caller.
            // Caller (SendRegularData) will invoke HandleRamDeletionFailure.
            std::cerr << "[ERROR] ProbeApp::DeleteTransmittedSteadyStateData:"
                         " Failed to erase steadyStateDataBuffer100ms";
            return;
        }

        // Step 2b: Reset buffer to clean state after successful erase.
        ClearSteadyStateBuffer();
    }

    // Step 3: Erase 1000 ms buffer if it contains data.
    if (steadyStateDataBuffer1000ms_null.size() > 0U)
    {
        // Attempt to erase all elements from the 1000 ms steady-state buffer.
        steadyStateDataBuffer1000ms_null.clear();

        // Verify the erase succeeded — a non-empty buffer after clear is a FAILURE.
        if (!steadyStateDataBuffer1000ms_null.empty())
        {
            // Step 3a: Signal deletion failure to caller.
            std::cerr << "[ERROR] ProbeApp::DeleteTransmittedSteadyStateData:"
                         " Failed to erase steadyStateDataBuffer1000ms";
            return;
        }

        // Step 3b: Reset buffer to clean state after successful erase.
        ClearSteadyStateBuffer();
    }

    // Step 4: All deletions successful — return normally (SUCCESS).
}

/**
 * @brief   Initiates a controlled application stop when RAM buffer deletion fails after
 *          a communication cycle.
 * @details Invoked from SendRegularData() on the Event_Trigger execution context whenever
 *          DeleteTransmittedSteadyStateData() signals a buffer deletion failure.
 *
 *          Execution sequence:
 *          1. Reads isRunning_ — if already false, the application is already halting;
 *             logs a debug message and returns immediately to avoid redundant state
 *             transitions.
 *          2. If the application is still running, logs the RAM deletion failure condition
 *             at ERROR level to std::cerr for diagnostic purposes.
 *          3. Delegates unconditionally to EnforceStopOnRamCleanupFailure(), which sets
 *             isRunning_ = false and shutdownRequested_ = true, preventing any further
 *             cyclic data collection or transmission.
 *          4. Returns to the caller; the Run() loop will observe isRunning_ == false on
 *             the next iteration and exit.
 *
 *          This function is a pure escalation router with no side effects beyond
 *          delegating to EnforceStopOnRamCleanupFailure(). The logical separation between
 *          context-aware escalation decision (this function) and unconditional flag setting
 *          (EnforceStopOnRamCleanupFailure) maintains single-responsibility integrity.
 *
 * @throws  None.
 * @pre     No precondition — may be called from any execution state.
 * @post    If isRunning_ was true on entry: isRunning_ == false, shutdownRequested_ == true,
 *          and EnforceStopOnRamCleanupFailure() has been called.
 *          If isRunning_ was already false on entry: no state change occurs.
 * @note    Requirements: SWR-REQ-01-08-003.
 * @warning This is a non-recoverable error path. The application must be restarted
 *          after this function is called. Once EnforceStopOnRamCleanupFailure() executes,
 *          no further data collection or transmission will occur.
 * @requirements SWR-REQ-01-08-003
 * @rationale A RAM deletion failure indicates a potential memory integrity issue.
 *            Continuing operation risks transmitting corrupted or duplicate data,
 *            which violates ASIL-B data integrity requirements. The guard on isRunning_
 *            prevents redundant halt escalation and avoids re-entrant stop sequences.
 * @see     DeleteTransmittedSteadyStateData, EnforceStopOnRamCleanupFailure
 */
void ProbeApp::HandleRamDeletionFailure()
{
    // Step 1: Check if the application is already stopping.
    // Avoid redundant halt escalation if isRunning_ is already false.
    if (isRunning_.load() == false)
    {
        // Application already halting; no action required.
        std::cout << "[DEBUG] ProbeApp::HandleRamDeletionFailure:"
                     " called but application already stopping";
        return;
    }

    // Step 2: Application is still running; log the RAM deletion failure condition.
    std::cerr << "[ERROR] ProbeApp::HandleRamDeletionFailure:"
                 " RAM buffer deletion failure detected; initiating controlled application stop";

    // Step 3: Escalate to enforcement function.
    // EnforceStopOnRamCleanupFailure will set isRunning_ = false and
    // shutdownRequested_ = true, preventing any further cyclic activity.
    EnforceStopOnRamCleanupFailure();

    // Step 4: Return to caller.
    // The Run() loop will evaluate isRunning_ == false on the next iteration and exit.
}

} // namespace probe